### ISSUE TITLE
`ngc` resolves to ngResource

### ISSUE THREAD

**Issue by demisx** [atom-community/autocomplete-plus#169]
Atom: 0.158.0
Autocomplete: 0.22.14
Angularjs: 0.0.5

Typing `ngc` and hitting `Tab` auto completes to `ngResource` instead of Angular controller code snippet. Everything goes back to normal if I disable this package.

**Comment by joefitzgerald** [comment]
To enable strict matching, just enable the preference for it. Right now you have to manually set the preference, but it will be included in the preference UI in the next version of the package. This will prevent the fuzzy matching that allows `ngResource` to appear for the prefix `ngc`.

**Comment by demisx** [comment]
Sorry, where would I set this? I don't see this setting on the `Autocomplete Plus` settings page.
