### ISSUE TITLE
Atom always crashes each time i  try to type anything

### ISSUE THREAD

**Issue by lampropoi** [atom-community/autocomplete-plus#187]
After having installed autocomplete plus, I <b> cannot write anything</b> since I get the following type of errors:
Attempt to write the letter 't':

<code>
Uncaught TypeError: Expecting a function in instanceof check, but got undefined c:\Users\ioanna\Desktop\Atom\resources\app\src\view-registry.js:70
</code>

Atom is installed in Windows 8.1 and in order to enable the package to have been installed, I have manually added the Git path in the environmental parameters of my operating system.

Thank you in advance!

**Comment by ThemisB** [comment]
I have exactly the same problem. Atom is installed in Ubuntu 14.04

**Comment by joefitzgerald** [comment]
What other packages do you have installed? Run `apm list` in a terminal and paste the output.

**Comment by joefitzgerald** [comment]
Also, what version of atom are you running?

**Comment by ThemisB** [comment]
@joefitzgerald 

Built-in Atom packages (77)
├── archive-view
├── atom-dark-syntax
├── atom-dark-ui
├── atom-light-syntax
├── atom-light-ui
├── autocomplete
├── autoflow
├── autosave
├── background-tips
├── base16-tomorrow-dark-theme
├── base16-tomorrow-light-theme
├── bookmarks
├── bracket-matcher
├── command-palette
├── deprecation-cop
├── dev-live-reload
├── encoding-selector
├── exception-reporting
├── find-and-replace
├── fuzzy-finder
├── git-diff
├── go-to-line
├── grammar-selector
├── image-view
├── incompatible-packages
├── keybinding-resolver
├── language-c
├── language-coffee-script
├── language-css
├── language-gfm
├── language-git
├── language-go
├── language-html
├── language-hyperlink
├── language-java
├── language-javascript
├── language-json
├── language-less
├── language-make
├── language-mustache
├── language-objective-c
├── language-perl
├── language-php
├── language-property-list
├── language-python
├── language-ruby
├── language-ruby-on-rails
├── language-sass
├── language-shellscript
├── language-source
├── language-sql
├── language-text
├── language-todo
├── language-toml
├── language-xml
├── language-yaml
├── link
├── markdown-preview
├── metrics
├── open-on-github
├── package-generator
├── release-notes
├── settings-view
├── snippets
├── solarized-dark-syntax
├── solarized-light-syntax
├── spell-check
├── status-bar
├── styleguide
├── symbols-view
├── tabs
├── timecop
├── tree-view
├── update-package-dependencies
├── welcome
├── whitespace
└── wrap-guide

/home/themisb/.atom/packages (7)
├── atom-hack
├── autocomplete-paths@0.9.1
├── inline-autocomplete@0.3.3
├── linter@0.9.0
├── minimap@3.4.9
├── seti-syntax@0.2.1
└── seti-ui@0.5.1

Atom Version : 0.152.0

**Comment by joefitzgerald** [comment]
Two things: 

1. You're running an old version of atom. You should update to `0.165.0`
1. You don't have `autocomplete-plus` installed - you have `inline-autocomplete` installed - that is not this package. Uninstall it to fix your issue.

**Comment by ThemisB** [comment]
@joefitzgerald Problem solved after update thanks!

// I removed autocomplete-plus previously and i used the the inline-autocomplete instead. My mistake i thought i was using autocomplete-plus and posted the packages.

**Comment by lampropoi** [comment]
Thank you for your help! I I have updated atom and everythin works fine :+1:

**Comment by joefitzgerald** [comment]
No problem. In general, you should always do the following before submitting an issue:

1. Verify you have the package you think you have installed _actually_ installed
1. Verify you are running the latest version of Atom
1. Verify you have installed all package updates - particularly those that exist for the package in question

Happy new year!
