### ISSUE TITLE
Incorrect inserted suggestion

### ISSUE THREAD

**Issue by PavelVanecek** [atom-community/autocomplete-plus#188]
I found an issue: when I confirm the suggestion using keyboard shortcut, it inserts the word twice. Mouse-confirm is okay.

Correct behaviour (confirming with mouse):
![ac-p1](https://cloud.githubusercontent.com/assets/1100170/5596167/41fa0d48-9287-11e4-9343-58f911966373.gif)

The bug (confirming with enter):
![ac-p2](https://cloud.githubusercontent.com/assets/1100170/5596166/2772a34a-9287-11e4-83de-ae4d225fbcfe.gif)

This is not observable immediately, Atom relaunch fixes it. I'm not sure how to reproduce.
The issue only appears after several hours.

Update: it seems the extension adds that many letters, how many I *did not* type.
Example:
I type *reques* and confirm: it inserts *RREQUESTS*
I type *r* and confirm: it inserts *REQUESTREQUESTS*

Environment:

OSX 10.10
Atom 0.165.0
autocomplete-plus 1.1.0
// I have observed this issue on version 1.0.0 too

```
$ apm list
├── Stylus@0.4.0
├── atom-html-preview@0.1.3
├── atom-prettify@0.1.0
├── autoclose-html@0.13.0
├── autocomplete-plus@1.0.0
├── coffee-compile@0.8.4
├── color-picker@1.2.6
├── css-color-highlighting@0.2.4
├── editorconfig@0.2.2
├── error-status@0.3.1
├── file-icons@1.4.3
├── git-plus@4.3.0
├── highlight-line@0.9.2
├── highlight-selected@0.7.0
├── html2jade@0.7.0
├── language-ejs@0.1.0
├── language-jade@0.3.0
├── language-jsx@0.1.4
├── language-latex@0.4.1
├── language-r@0.1.1
├── line-ending-converter@0.4.0
├── minimap@3.4.9
├── minimap-color-highlight@3.0.3
├── minimap-find-and-replace@3.0.4
├── minimap-git-diff@3.0.11
├── minimap-highlight-selected@3.0.0
├── monokai@0.9.0
├── pane-layout-plus@0.4.0
├── pretty-json@0.3.1
├── preview-tabs@0.1.6
├── save-session@0.11.2
├── ssh-config@0.10.0
├── todo-show@0.6.0
└── view-tail-large-files@0.1.6
```

`keymap.cson`:
```
".autocomplete-plus":
  "enter": "autocomplete-plus:confirm"
```

**Comment by PavelVanecek** [comment]
Update: observed in Atom 0.166.0 too

**Comment by philidem** [comment]
I've also been experiencing this problem and restarting Atom seems to get it back to a working state (for a little while, at least). A more permanent solution would be much appreciated.

**Comment by erikLovesMetal** [comment]
I too have been noticing this.  It will append the confirmed autocomplete selection to the previously typed text that triggered the autocomplete suggestion.   Other that that its killer

**Comment by joefitzgerald** [comment]
I can confirm that I have also observed this. We will create a test to reproduce and then fix in #186

**Comment by joefitzgerald** [comment]
I cannot reproduce this reliably with the exact same text:

```
#!/bin/bash

REQUESTS=$1
if [ -z "$REQUESTS"]; then

ab -n $1 -c 5 -p postfile 127.0.0.1:63333/
```

**Comment by PavelVanecek** [comment]
The text was selected as an example. I don't know the real cause, the best I can come with is "every couple hours."

**Comment by marvwhere** [comment]
i don't want to open another issue, i still have this bug. 

maybe i will try to fix this by my self later the day. but is it known that its still open?

![codepaste](https://cloud.githubusercontent.com/assets/414174/6167000/91dd7fee-b2b6-11e4-93ba-a0f1509a2a52.gif)

**Comment by joefitzgerald** [comment]
What version of atom and autocomplete-plus are you running?

**Comment by marvwhere** [comment]
atom: 0.179.0
autocomplete+: 2.1.6

thats why i'm wondering
