### ISSUE TITLE
Autocomplete is disruptive to Emmet

### ISSUE THREAD

**Issue by matthew-b-payne** [atom-community/autocomplete-plus#192]
When typing in an html file typing just html tags presents non relevant suggestions when I just want to hit tab and expand the emmet expression.  

Emmet with html auto complete seems to work in harmony in sublime text, so this should be able to be sorted out.

**Comment by joefitzgerald** [comment]
This can be easily fixed by changing your keybinding. Open `Preferences > Packages > autocomplete-plus > Settings` and set `Keybind(s) For Confirming A Suggestion` to `enter`.
