### ISSUE TITLE
Installing in windows

### ISSUE THREAD

**Issue by JeancarloPerez** [atom-community/autocomplete-plus#193]
Why I can´t install this package in my pc?
I have windows 7.

This is the error when I try install:
<code>
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http 200 https://registry.npmjs.org/grim
npm http 200 https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http GET https://registry.npmjs.org/grim/-/grim-1.1.0.tgz
npm http 200 https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/event-kit/-/event-kit-1.0.1.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http 200 https://registry.npmjs.org/fuzzaldrin
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fuzzaldrin/-/fuzzaldrin-2.1.0.tgz
npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm http 200 https://registry.npmjs.org/grim/-/grim-1.1.0.tgz
npm http 200 https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http 200 https://registry.npmjs.org/event-kit/-/event-kit-1.0.1.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http 200 https://registry.npmjs.org/fuzzaldrin/-/fuzzaldrin-2.1.0.tgz
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/brace-expansion
npm http 200 https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/coffeestack/-/coffeestack-0.7.0.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/brace-expansion
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http GET https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http GET https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http 200 https://registry.npmjs.org/coffeestack/-/coffeestack-0.7.0.tgz
npm http 200 https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http 200 https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 200 https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/coffee-script/-/coffee-script-1.7.1.tgz
npm http 200 https://registry.npmjs.org/mixto
npm http 200 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http GET https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 200 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.0.tgz
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\eperez\\.atom\\.apmrc" "install" "C:\\Users\\eperez\\AppData\\Local\\Temp\\d-115014-6764-105y1oh\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\eperez\AppData\Local\Temp\apm-install-dir-115014-6764-7xsvch
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http 200 https://registry.npmjs.org/coffee-script/-/coffee-script-1.7.1.tgz
npm http 200 https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http 200 https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.0.tgz
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm
</code>

**Comment by joefitzgerald** [comment]
Please read the error message: 
> npm ERR! Failed using git. npm ERR! This is most likely not a problem with npm itself. npm ERR! **Please check if you have git installed and in your PATH.**
> [...]
> npm ERR! code ENOGIT

git must be installed, and must be available on your system PATH. You may need to reboot for your system PATH to take hold.

**Comment by JeancarloPerez** [comment]
thanks for your comments!
