### ISSUE TITLE
Error when trying to install 

### ISSUE THREAD

**Issue by toddy86** [atom-community/autocomplete-plus#195]
When I attempt to install autocomplete-plus I receive the following error log... Any help would be greatly appreciated. New to programming so autocomplete is a heaven sent. 

Installing “autocomplete-plus@1.1.0” failed.Hide output…

npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/fuzzaldrin
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/property-accessors
npm ERR! Error: ENOENT, lstat 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\source-map\source-map-generator.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Todd\\.atom\\.apmrc" "install" "c:\\Users\\Todd\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-plus\\1.1.0\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\source-map\source-map-generator.js
npm ERR! fstream_path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\source-map\source-map-generator.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Todd\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js'
npm ERR! error rolling back  grim@1.1.0 { [Error: EPERM, unlink 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\Todd\\AppData\\Local\\Temp\\apm-install-dir-115016-3528-6rc5vc\\node_modules\\autocomplete-plus\\node_modules\\grim\\node_modules\\coffeestack\\node_modules\\coffee-script\\lib\\coffee-script\\parser.js' }
npm ERR! EEXIST, mkdir 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map'
File exists: C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map
Move it away, and try again. 

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Todd\\.atom\\.apmrc" "install" "c:\\Users\\Todd\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-plus\\1.1.0\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map
npm ERR! fstream_path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\README.markdown
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack c:\Users\Todd\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack c:\Users\Todd\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js'
npm ERR! error rolling back  autocomplete-plus@1.1.0 { [Error: EPERM, unlink 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\Todd\\AppData\\Local\\Temp\\apm-install-dir-115016-3528-6rc5vc\\node_modules\\autocomplete-plus\\node_modules\\grim\\node_modules\\coffeestack\\node_modules\\coffee-script\\lib\\coffee-script\\parser.js' }
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Todd\\.atom\\.apmrc" "install" "c:\\Users\\Todd\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-plus\\1.1.0\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm ERR! Error: ENOENT, lstat 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\example.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Todd\\.atom\\.apmrc" "install" "c:\\Users\\Todd\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-plus\\1.1.0\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\example.js
npm ERR! fstream_path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\example.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Todd\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Todd\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Todd\\.atom\\.apmrc" "install" "c:\\Users\\Todd\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-plus\\1.1.0\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js
npm ERR! fstream_path C:\Users\Todd\AppData\Local\Temp\apm-install-dir-115016-3528-6rc5vc\node_modules\autocomplete-plus\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\parser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Todd\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm

**Comment by joefitzgerald** [comment]
Same response as #193. Please read the error message before logging an issue.
