### ISSUE TITLE
FuzzyProvider Should Remove Words Which Are No Longer In Any Open Buffer

### ISSUE THREAD

**Issue by DiThi** [atom-community/autocomplete-plus#196]
* Open a new buffer.
* Write `bogos = 1`, then press enter.
* Correct that word to "bogus" by replacing one letter.

Now it's only autocompleting "bogos" and not "bogus". If you write "bogus" later, both versions are in the autocompletion list.

There's no way to remove words with typos without closing the document or rebooting atom (if configured to use other buffers).

When typing a word then pressing enter, it's not added to autocompletion (hence the `= 1` in the example).

**Comment by joefitzgerald** [comment]
What is the filetype of the file you opened prior to typing `bogos = 1`? We will create a test and then fix in #186.

**Comment by DiThi** [comment]
No type, just creating a new empty document. It also happened to me with CoffeeScript and Python.

**Comment by joefitzgerald** [comment]
Got it. Thanks!

**Comment by DiThi** [comment]
I think this is a bug. Also the new title doesn't reflect that changed words and words in end of line aren't added. But maybe that should be filed in a different issue?

**Comment by joefitzgerald** [comment]
Bug or enhancement, it doesn't change anything :) Reality is the current FuzzyProvider implementation is a holdover from `autocomplete`, and needs significant enhancement to be more useful. If you would like to open additional issues feel free, or edit this issue to describe the use cases you'd like covered by a set of tests so we can lock in the behavior.

**Comment by joefitzgerald** [comment]
As far as I can tell from the code, saving the open buffer should cause the word list to be rebuilt. If that doesn't remove the extraneous suggestion, we have an issue. I'm a little hesitant to rebuilt the word list in a single buffer continuously, so despite having a test for this that reliably reproduces it, I'm not sure the fix should be put in place for performance reasons. Thoughts @park9140?

```coffeescript
it "removes words from the wordlist when they no longer exist in any open buffers", ->
      provider = autocompleteManager.providerManager.fuzzyProvider

      expect(provider.wordList.indexOf("bogos")).toEqual(-1)
      editor.insertText("bogos = 1")
      editor.insertText(" ")
      expect(provider.wordList.indexOf("bogos")).not.toEqual(-1)
      expect(provider.wordList.indexOf("bogus")).toEqual(-1)
      editor.backspace() for [1..7]
      editor.insertText("us = 1")
      editor.insertText(" ")
      expect(provider.wordList.indexOf("bogus")).not.toEqual(-1)
      expect(provider.wordList.indexOf("bogos")).toEqual(-1)
```

**Comment by park9140** [comment]
@joefitzgerald , honestly, I don't think we should continuously rebuild, this scan already drastically drops performance in large files.
