### ISSUE TITLE
Didn't replace initial text

### ISSUE THREAD

**Issue by rizqinizamil** [atom-community/autocomplete-plus#197]
Hi there,

I have a problem when I'm typing and suggestion is showed then I hit enter/tab, initial text didn't replace with chosen suggestion. For example I want to type "text-align", the suggestion is showed when I'm typing "text" then I hit enter/tab "text-align". Complete text will be "text-text-align" not "text-align".

Any thoughts?

**Comment by nick-desteffen** [comment]
Try updating it.  I had the same problem and wanted to (╯°□°）╯︵ ┻━┻ 

I was gonna disable it and noticed there was a new version released, updating seemed to fix this problem.

**Comment by joefitzgerald** [comment]
See also #188. This is a known issue, which we will be fixing in #186.

**Comment by wbaes** [comment]
Sorry to reopen this, but after updating to the most recent version I'm encountering this exact same problem.
