### ISSUE TITLE
Pastes twice

### ISSUE THREAD

**Issue by steelbrain** [atom-community/autocomplete-plus#198]
I am having a problem on Atom v169 on Windows/Linux with AutoComplete-Plus package. Whenever this package is enabled, everytime I paste stuff, it gets pasted twice.

Not sure if it's a problem in some other package. Please advice.

**Comment by steelbrain** [comment]
Steps to reproduce
 - Move `~/.atom` to `~/.atom-bkp`
 - `apm install autocomplete-plus`
 - Create a new file called `main.hh`
 - Write something and then coppy it.
 - Write `$main` or something to make the autocomplete dropdown appear.
 - While you can see it, Paste using CTRL + V
Et Viola! It'll double paste it.

**Comment by steelbrain** [comment]
This has been fixed by upgrading both Atom & Autocomplete-plus to the latest versions.

**Comment by joefitzgerald** [comment]
:tasa:
