### ISSUE TITLE
It disturbs the transforming with Google IME

### ISSUE THREAD

**Issue by kyoh86** [atom-community/autocomplete-plus#200]
When I'm using the Google IME, the Autocomplete-Plus shows a suggestions and the ATOM deletes untransformed words.
So I have to set the "Show Suggestions On Keystroke" to off, which is too inconvenient.

Showing suggestions, determine if IME is on, the Autocomplete-Plus should cancel to do it.

**Comment by kyoh86** [comment]
That's not fixed!

**Comment by joefitzgerald** [comment]
Please try again in v2.1.1.

**Comment by joefitzgerald** [comment]
I believe this is fixed in v2.1.3. Please try and let me know if this is not fixed.
