### ISSUE TITLE
Allow Anonymous Or Actual Snippets To Be Provided As Suggestions And Expanded When Confirmed

### ISSUE THREAD

**Issue by joefitzgerald** [atom-community/autocomplete-plus#201]
- [x] Expand snippet when suggestion is confirmed
- [ ] Allow providers to specify that a suggestion includes an anonymous snippet that should be inserted
- [ ] Ensure triggering of autocomplete doesn't conflict with completion of snippet expansion (e.g. if multiple snippet arguments need to be satisfied)
- [ ] Filter snippets from suggestions when the cursor is currently inside of a snippet that is being expanded

**Comment by joefitzgerald** [comment]
Sounds like @park9140 has an implementation in park9140/atom-typescript-tools. Let's bring it in-house!

**Comment by benogle** [comment]
This is out!
