### ISSUE TITLE
Is the new provider api available

### ISSUE THREAD

**Issue by basarat** [atom-community/autocomplete-plus#205]
I'm having trouble getting the new API : https://github.com/atom-community/autocomplete-plus/wiki/Provider-API to work. Is it deployed? I see the version number to be `1.1.0` https://atom.io/packages/autocomplete-plus

**Comment by joefitzgerald** [comment]
See #186. This will be released in the next 24 hours.

**Comment by joefitzgerald** [comment]
This is now in master. Will be released @ 8:00 am Mountain (US) time tomorrow morning.

**Comment by basarat** [comment]
@joefitzgerald great job with documenting the new API. Thanks, can't wait to use it!
