### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by acogent** [atom-community/autocomplete-plus#206]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:53:11)
Object.activate (/home/acogent/.atom/packages/autocomplete-plus/lib/autocomplete.coffee:31:31)
```

**Comment by joefitzgerald** [comment]
See #186, and watch the release that hits in about 3 minutes ;)
