### ISSUE TITLE
Ability to provide `comments` against completions

### ISSUE THREAD

**Issue by basarat** [atom-community/autocomplete-plus#209]
I see `labels`. Is there a way to provide `hover` comments?

**Comment by joefitzgerald** [comment]
I think this would be a nice enhancement and would also help out @tststs.

**Comment by basarat** [comment]
I am working on this based on off of what @tststs did. These are the events that are handled : https://github.com/tststs/atom-ternjs/blob/4616908855ac2efd1e2f3a1129a4eb4e47b78b52/lib/atom-ternjs-provider.coffee#L163-L175 

Would be great if we could get `did-show` and `did-hide` : https://github.com/atom-community/autocomplete-plus/blob/9610565ae688ffd9b07cc8b850ad7dd562f5e969/lib/suggestion-list.coffee#L77-L100  

@tststs do you show comments for the *first* item in the list. Also its not certain that the list contains *only* the items you contain as far as I can tell.

**Comment by joefitzgerald** [comment]
I don't think you'd need did-show and did-hide if this is handled in the core. It sounds like it would be more beneficial to extend the suggestion object such that you can provide additional documentation that can be included in a "tooltip" or similar, activated when a suggestion is selected or hovered over.

@park9140 has considered using label for this and taking it out of the list by default, allowing an icon on the left to be used to denote the "type" / "kind" of suggestion (e.g. Func, const, etc.).

**Comment by basarat** [comment]
Alright any more work I'll try to do as a PR. Thing is I love type safety too much :sob: to bring my self to coffeescript. Also my queue is quite long atm. : https://github.com/TypeStrong/atom-typescript/issues?q=assignee%3Abasarat+is%3Aopen Thanks for your interest though!
