### ISSUE TITLE
Consider changing the default opacity on `label`

### ISSUE THREAD

**Issue by basarat** [atom-community/autocomplete-plus#214]
The default `opacity` on label's `span` is `0.3` which makes any form of color coding labels effectively useless. E.g. :

![image](https://cloud.githubusercontent.com/assets/874898/5971108/bf67dca8-a892-11e4-83f5-d8ab950106ba.png)

The actual color I am *forced* to use is quite vibrant : 
![image](https://cloud.githubusercontent.com/assets/874898/5971122/efc7219c-a892-11e4-95f3-f958085c83ea.png)

If I change it to something like `0.6` color coding the labels is much more useful:

![image](https://cloud.githubusercontent.com/assets/874898/5971128/266d43fc-a893-11e4-9fa6-e18d8f656ab7.png)

I haven't found other colors except green/white that cut out of the `0.3` opacity.

**Comment by joefitzgerald** [comment]
What if we added a colored background, like a roundrect? And then set the opacity of the text back to zero.

**Comment by basarat** [comment]
> What if we added a colored background, like a roundrect? And then set the opacity of the text back to zero.

I'd need an example to understand what you mean here. Meanwhile [I've done this](https://github.com/TypeStrong/atom-typescript/commit/4c7ad73750bda18fc21f15c5abefcf1c0b541944) and you can see the difference it makes (it feels like it comes to life IMHO).

**Comment by park9140** [comment]
@basarat, #216 cleans up this partially at least.  I'm still working on a redesign options for the dropdown, that may affect your options here.

**Comment by joefitzgerald** [comment]
Closing this in deference to #230.
