### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by jinmatt** [atom-community/autocomplete-plus#217]
`/Users/jinmatt/.atom/packages/autocomplete-plus/lib/provider.coffee:46`

Stack Trace
```
TypeError: Cannot read property 'apply' of undefined
  at Object.module.exports.Provider.buildSuggestionsShim [as requestHandler] (/Users/jinmatt/.atom/packages/autocomplete-plus/lib/provider.coffee:46:22)
  at /Users/jinmatt/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:115:39
  at Array.map (native)
  at AutocompleteManager.module.exports.AutocompleteManager.scatterRequest (/Users/jinmatt/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:114:27)
  at AutocompleteManager.scatterRequest (/Users/jinmatt/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.runAutocompletion (/Users/jinmatt/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:109:6)
  at /Users/jinmatt/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
```

**Comment by joefitzgerald** [comment]
@jinmatt Can you please let me know which packages you have installed?

**Comment by akhalizev** [comment]
@joefitzgerald  I have the same problem. Reinstalled autocomplete+ and it works until Atom relaunch. 
My other installed packages is: linter, Stylus, wordpress-api, autoprefixer, 
color-picker, emmet, foundation5-snippets, language-jade, layout-manager, autocomplete-gocode, linter-jshint, linter-write-good, markdown-writer, minimap, term2, wordpress, wp-snippets.

Core autocomplete package works.

**Comment by joefitzgerald** [comment]
See #211  - uninstall `autocomplete-gocode`; it is deprecated and the functionality is in `go-plus`.

**Comment by joefitzgerald** [comment]
I will leave this open for a short while so that others who get this error see the resolution.

**Comment by yasuyuki** [comment]
I don't have `autocomplete-gocode`, but same problem is happend.
I installed below.

auto-update-packages, v0.2.2
autocomplete-plus, v2.0.3
change-case, v0.4.0
dash, v1.0.2
japanese-wrap, v0.2.3
linter, v0.10.1
linter-rubocop, v0.2.1
live-archive, v0.1.10
rsense, v0.6.0

**Comment by joefitzgerald** [comment]
rsense is still using the old, deprecated API, but in a way that is incompatible with the new version of the package. https://github.com/rsense/atom-rsense/issues/1 was opened a month ago to address this, but I'm not sure @edubkendo has had the time to address it.

**Comment by joefitzgerald** [comment]
@yasuyuki If you update to v2.0.4, you should not get an error from autocomplete-plus anymore. `rsense` will not work until that package has been updated to work with the new API.

**Comment by jinmatt** [comment]
@joefitzgerald : Thanks for pointing out. I had `autocomplete-gocode` installed, switched to `go-plus` now.

**Comment by yasuyuki** [comment]
I updated to 2.0.6, I didn't meet any errors. Thank you.
