### ISSUE TITLE
High CPU loads after updating to version 2.0.*

### ISSUE THREAD

**Issue by splendido** [atom-community/autocomplete-plus#218]
On Ubuntu 14.04 with Atom@0.176.0

I needed to disable it, writing went not responsive at all :(

**Comment by splendido** [comment]
I did some tests rolling back the version.
It works flawlessly with 1.1.0, but as soon as I install `2.0.0`, `2.0.1`, `2.0.2`, or `2.0.2` the CPU get to 100% usage as soon as I start typing something.

I'm available to provide more details about my envirnoment and the list of other packages I have installed in case this could help.

Tnx!

**Comment by joefitzgerald** [comment]
Do you have autocomplete paths installed?

**Comment by splendido** [comment]
yes :(

...I've just tried to update to `2.0.3` and disable `autocomplete-paths`: no more CPU spikes!
Is this a known bug?

**Comment by joefitzgerald** [comment]
Yes, it was reported yesterday. I will try to get a fix out today.

**Comment by splendido** [comment]
Ok, so it's probably [this issue](https://github.com/atom-community/autocomplete-paths/issues/39) right?

Tnx!

**Comment by joefitzgerald** [comment]
Yep.

**Comment by joefitzgerald** [comment]
This is fixed in `autocomplete-paths` `v1.0.1`. Please update.

**Comment by splendido** [comment]
Brilliant, tnx!
