### ISSUE TITLE
Compatibility Issue With auto-save Package

### ISSUE THREAD

**Issue by Saucy** [atom-community/autocomplete-plus#221]
Hi, I'm having a few problems with v2.0.3.

I'm using Atom v0.176.0, Windows 7 Ultimate 64-bit.
The only autocomplete-plus settings I've changed is "Keymap for confirming a suggestion" to "Enter".

- The popup list appears for a few seconds and then disappears.
- I noticed was the cursor is hidden once the popup appears.
- After writing a keyword (in this case `echo`) the space I make afterwards gets discarded and the whole thing becomes a long word.

I'll try illustrate with two gifs I made.

Here's how my **v1.1.0** work:
![1 1 0](https://cloud.githubusercontent.com/assets/2084555/5986917/80abfe08-a910-11e4-8fa0-70d9e2737049.gif)

This is how my **v2.0.3** work:
![2 0 3](https://cloud.githubusercontent.com/assets/2084555/5986919/83c105ac-a910-11e4-97b1-d421f1c9c2fb.gif)

Is there anything else you need to know? I'll try my best to provide the information needed.

**Comment by joefitzgerald** [comment]
Can you please let us know which packages you have installed? I.e. the output from `apm list`.

**Comment by Saucy** [comment]
```
Built-in Atom packages (83)
├── archive-view@0.44.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.46.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.40.0
├── autocomplete@0.43.0
├── autoflow@0.21.0
├── autosave@0.20.0
├── background-tips@0.21.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.69.0
├── command-palette@0.34.0
├── deprecation-cop@0.33.0
├── dev-live-reload@0.39.0
├── encoding-selector@0.17.0
├── exception-reporting@0.21.0
├── find-and-replace@0.156.0
├── fuzzy-finder@0.65.0
├── git-diff@0.49.0
├── go-to-line@0.30.0
├── grammar-selector@0.44.0
├── image-view@0.47.0
├── incompatible-packages@0.21.0
├── keybinding-resolver@0.27.0
├── language-c@0.37.0
├── language-clojure@0.10.0
├── language-coffee-script@0.39.0
├── language-css@0.26.0
├── language-gfm@0.63.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.28.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.55.0
├── language-json@0.11.0
├── language-less@0.24.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.10.0
├── language-php@0.20.0
├── language-property-list@0.8.0
├── language-python@0.30.0
├── language-ruby@0.47.0
├── language-ruby-on-rails@0.18.0
├── language-sass@0.31.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.15.0
├── language-toml@0.15.0
├── language-xml@0.27.0
├── language-yaml@0.22.0
├── link@0.29.0
├── markdown-preview@0.126.0
├── metrics@0.41.0
├── notifications@0.26.0
├── one-dark-syntax@0.2.0
├── one-dark-ui@0.2.0
├── one-light-syntax@0.2.0
├── one-light-ui@0.1.0
├── open-on-github@0.32.0
├── package-generator@0.37.0
├── release-notes@0.47.0
├── settings-view@0.174.0
├── snippets@0.70.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.51.0
├── status-bar@0.57.0
├── styleguide@0.42.0
├── symbols-view@0.79.0
├── tabs@0.64.0
├── timecop@0.28.0
├── tree-view@0.148.0
├── update-package-dependencies@0.7.0
├── welcome@0.21.0
├── whitespace@0.28.0
└── wrap-guide@0.31.0

.atom\packages (26)
├── alignment@1.1.4
├── autocomplete-plus@1.1.0
├── color-picker@1.4.4
├── docblockr@0.5.8
├── editor-stats@0.16.0
├── editorconfig@0.3.0
├── git-blame@0.3.3
├── git-tab-status@1.5.3
├── goto@1.7.0
├── halflife@1.0.0
├── highlight-line@0.9.3
├── highlight-selected@0.7.0
├── linter@0.10.1
├── linter-cpplint@0.1.3
├── linter-csslint@0.0.11
├── linter-htmlhint@0.0.8
├── linter-javac@0.1.3
├── linter-jshint@0.1.0
├── linter-jsonlint@0.1.2
├── linter-lua@0.1.3
├── linter-php@0.0.11
├── minimap@3.5.6
├── remember-session@0.5.1
├── seti-ui@0.6.3
├── SFTP-deployment@0.5.0
└── todo-show@0.6.0
```

**Comment by Saucy** [comment]
I disabled all community packages, but the same thing still happens in v2.0.3.

**Comment by joefitzgerald** [comment]
Do you have auto-save enabled?

**Comment by Saucy** [comment]
Yes I have.

**Comment by joefitzgerald** [comment]
And does the problem go away when you disable auto-save?

**Comment by Saucy** [comment]
Yeah, disabling it seems to fix the problem I'm having.

**Comment by joefitzgerald** [comment]
That's a bug. Thanks for identifying it.

**Comment by Saucy** [comment]
Glad to help, thanks for quick response and help! :)

**Comment by park9140** [comment]
@Saucy, after disabling all the community packages did you restart atom?

**Comment by joefitzgerald** [comment]
@Saucy I wrote a test to reproduce but things seem to work fine with autosave - both via the test and via manual testing. Could you please post your user config (`File > Open Your Config`)?

**Comment by joefitzgerald** [comment]
@Saucy I was able to reproduce this and believe I have fixed it. We also have a test to reproduce the behavior, to prevent a future regression. Thanks again for bearing with us as we figured out the root cause.

**Comment by Saucy** [comment]
@park9140 No I didn't think that was necessary, as I've got the impression everything changes ASAP in Atom. I'll try restarting after disabling all community packages.

@joefitzgerald Okay. Do you want me to post my user config file anyway?

**Comment by joefitzgerald** [comment]
Wouldn't hurt, but if you still keep having issues, yes. 

Please retest with autosave enabled?

**Comment by Saucy** [comment]
Original user config

```
"*":
  "exception-reporting":
    userId: "afaece41-573d-402d-6eda-4eac08dde68a"
  welcome:
    showOnStartup: false
  metrics:
    userId: "f01dc1e592bf80cdeedef0cef7f570e5d3ed64f5"
  editor:
    fontFamily: "Ubuntu Mono"
    fontSize: 14
    showIndentGuide: true
    autoIndentOnPaste: false
    scrollPastEnd: true
    useShadowDOM: false
    invisibles: {}
    zoomFontWhenCtrlScrolling: false
  core:
    disabledPackages: [
      "git-blame"
      "background-tips"
      "SFTP-deployment"
      "sublime-tabs"
      "color-picker"
      "docblockr"
      "editor-stats"
      "linter-javac"
      "linter-cpplint"
      "autocomplete"
    ]
    themes: [
      "seti-ui"
      "halflife"
    ]
  "git-log":
    fontScale: 1
  linter:
    lintOnChangeInterval: 2000
    showErrorInline: true
    statusBar: "Show all errors"
  autosave:
    enabled: true
  whitespace:
    ignoreWhitespaceOnCurrentLine: false
  autocomplete:
    includeCompletionsFromAllBuffers: true
  minimap:
    displayPluginsControls: false
  "highlight-selected":
    onlyHighlightWholeWords: true
  "spell-check": {}
  "remember-session":
    x: -8
    y: -8
    width: 1936
    height: 1056
    treeWidth: 200
  "autocomplete-plus":
    confirmCompletion: "enter"
```

**Comment by Saucy** [comment]
I noticed as I was gonna post the user config that I had Shadow DOM **disabled**.

Using autocomplete-plus v2.0.6.

I've been testing with:
- Autosave always on
- All community packages enabled and disabled
- Shadow DOM enabled and disabled (switched between enabled/disabled all packages during this as well)
- Restarted Atom after each enable/disable

This gif shows what happens if I have Shadow DOM **disabled** (delay before suggestions are shown are set to 200).
- The first echo line I wait for the list to appear and use my key for confirming suggestion (enter).
- The second echo line I don't wait for the list to appear after `echo` but I do wait for the list to appear for `$someVariable`.

![44](https://cloud.githubusercontent.com/assets/2084555/5990350/715163fc-a9ac-11e4-9d85-ab106fdcb4e5.gif)

However I cannot reproduce this behavior if Shadow DOM is **enabled** (with all packages enabled, etc).

**Comment by joefitzgerald** [comment]
Yeah, we're not going to support Shadow DOM **disabled**. That option will be removed soon (I assume, prior to 1.0).

**Comment by Saucy** [comment]
Yeah that's understood. I remember I disabled it early on because it was messing with some other packages. Just forgot to enable it after a while.

Thanks for taking your time to help me. :)
