### ISSUE TITLE
Have suggestions display something other than what is expanded

### ISSUE THREAD

**Issue by sveale** [atom-community/autocomplete-plus#223]
Is it possible to display something other than what is expanded (without using label)?
Example would be that "asdf" is shown in suggestions, but when it is expanded "1234" replaces prefix.
Maybe add another variable to suggestions such as "displayName".

I imagine that snippets could be used to achieve this, but this seems like a bad choice.

**Comment by joefitzgerald** [comment]
Yeah, I plan to use snippets to achieve this for go-plus. 

Under what other circumstances would you want to display one thing and replace with another?

I can see how insertion of additional content for a snippet (beyond what I see in the suggestion list) makes sense, and should not be overly suprising. I worry that showing `asdf` and inserting `1234` might come across as confusing / not predictable behavior. Obviously your example is contrived - so I suppose I'm asking: what's the real use case?

**Comment by sveale** [comment]
What I had in mind was displaying the entire function signature as _word_, using _label_ to denote the "kind" of suggestion and when/if tooltips became available use that to display more verbose information such as explanation of what the function does. Upon expansion only the function name should replace prefix.

I realize that this can be done with snippets, but it seems overly complicated to use snippets if I'm not doing expansion of parameters.

**Comment by joefitzgerald** [comment]
So - once we can insert anonymous snippets for you, why wouldn't you expand the entire function signature?

One of the reasons we're moving the label to a tooltip - style display is the suggestion list can become extremely cluttered - use my go-plus gocode provider for example. I put the full function signature in the label, and just what will be replaced as the word. It can lead to a very, very wide suggestion list that takes over the window visually.

**Comment by sveale** [comment]
Lazyness. Haven't looked into how I can use anonymous snippets yet, but I guess I'll do that now :)

**Comment by joefitzgerald** [comment]
I guess now I need to add the ability to insert anonymous snippets for you :) @park9140 has an existing implementation in atom-typescript-tools that we're going to move into the core.

**Comment by joefitzgerald** [comment]
See #201 for anonymous snippets insertion.

**Comment by sveale** [comment]
I though snippets were already supported (ref. wiki)? Anyhow, thanks for the feedback :)

**Comment by joefitzgerald** [comment]
Snippet expansion is (I.e. For snippets in the grammar, or in user snippets). Anonymous snippets are not implemented yet. I'll try to get that added today.

**Comment by joefitzgerald** [comment]
The wiki's definition of how you would indicate a suggestion is a snippet and provide the anonymous snippet is accurate and shouldn't hange though.

**Comment by sveale** [comment]
Allright great, thanks again for the help and a great package.
