### ISSUE TITLE
Yet another code completion failure

### ISSUE THREAD

**Issue by superghostmaster** [atom-community/autocomplete-plus#224]
Looking for Sublime alternatives on OSX and Atom is #3 so far today that claims to have autocompletion working, claims to have code suggestions working and it simply does not.

This is a FUNDAMENTAL feature in a quality code editor.  It works in Sublime, it works in TextMate, it does NOT work in Atom.

I get it - it's lazy.  But it make me FAR more efficient, far fewer mistakes and simply makes coding easy.

Please, for the love of god, before you release a "feature" as working - make sure it works.

None of the code suggestions work, the code completion with tab is FUBAR and completely illogical - iife for a completed function??? WTF is that?

Look @ Sublime snippets & completion.  That's how it should work.  This Tern "support" is junk - WTF do I need lint running at all times for if it can REVIEW my code - then it should be able to SUGGEST completions, too.

**Comment by joefitzgerald** [comment]
Change your attitude buddy. We're volunteers working on this on evenings and weekends.
