### ISSUE TITLE
Some linter changes

### ISSUE THREAD

**Issue by benogle** [atom-community/autocomplete-plus#228]
To be consistent with core I am proposing two things:

1. Requires not wrapped in parens `fs = require('fs')` -> `fs = require 'fs'`
1. Only allow double quotes on strings in spec `describe` and `it` methods. They often contain contractions and generally `'`. We have taken to using double quotes in this case. Also the coffee `de` and `i` snippets generate specs with double quotes.

**Comment by joefitzgerald** [comment]
The following should be prefaced by my general desire to get to a `coffeelint.json` which enforces core standards. In this, I defer entirely to you.

> 1. Requires not wrapped in parens fs = require('fs') -> fs = require 'fs'

What's your opinion on `(` `)` for function invocations? We could have a custom rule that allows `require 'fs'` but doesn't allow `myPack.doThis withThat`. I find the latter (while idiomatic CoffeeScript) poor from a readability perspective.

> 2. Only allow double quotes on strings in spec describe and it methods. They often contain contractions and generally '. We have taken to using double quotes in this case. Also the coffee de and i snippets generate specs with double quotes.

It's easy to `''` or use `cannot` in place of `can't`, etc. Wouldn't it be better to change the `de` and `i` snippets to generate specs with single quotes? (I realize the absurdity of that suggestion, fwiw).

---

Per the prior statement, please feel free to update coffeelint.json to match the core standards - they are what matter, in particular for this project. It currently reflects my standards, which are not yours, and consequently lower in priority :smile:.

**Comment by joefitzgerald** [comment]
Interestingly, coffeelint is smart enough on the double quote rule to allow double quotes when you use `'` (to avoid escaping). So yeah, the issue is the snippets generate `"` by default. Should they?

**Comment by joefitzgerald** [comment]
See also: https://github.com/atom/language-coffee-script/pull/49

**Comment by benogle** [comment]
> What's your opinion on ( ) for function invocations?

In most cases, I agree with you. There are a couple cases where we use naked function calls: 

* requires
* spec matchers. So `expect('a').toBe 'a'`
* when there is a function or object at the end of the call

On the quote front, I totally agree with nathan's comment: https://github.com/atom/language-coffee-script/pull/49#issuecomment-72698786

**Comment by joefitzgerald** [comment]
I toned down the coffeelint.json config, and have it warning now. I need to write a few custom rules to allow naked requires, naked spec matchers, and double quotes in specs. It already permits when there is a function or object at the end of the call.

Once the rules are there, I will ignore implicit parens and double quotes, and use the custom rules instead.
