### ISSUE TITLE
atom.service is deprecated

### ISSUE THREAD

**Issue by ghyde** [atom-community/autocomplete-plus#229]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
ProviderManager.module.exports.ProviderManager.consumeApi (/Users/user/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:110:28)
```

**Comment by joefitzgerald** [comment]
Yes, we're aware of this - see https://github.com/atom/atom#5277

**Comment by joefitzgerald** [comment]
This is fixed. Please update.

**Comment by koleesch** [comment]
I have this issues too. My version of atom is 0.177.0.

**Comment by joefitzgerald** [comment]
Update autocomplete-plus. This is fixed.
