### ISSUE TITLE
Specs broken on master -- related to services

### ISSUE THREAD

**Issue by benogle** [atom-community/autocomplete-plus#236]
I'm at 09695389d92ecbc732b5aecb39c4e552d875a97a

![screen shot 2015-02-03 at 5 14 26 pm](https://cloud.githubusercontent.com/assets/69169/6033237/2193b4dc-abc8-11e4-95bd-0df770d2ba2e.png)

**Comment by joefitzgerald** [comment]
Hmm... Travis is passing. You done an apm install?

**Comment by joefitzgerald** [comment]
And are you on 0.177.0? Required for atom.packages.serviceHub.

**Comment by joefitzgerald** [comment]
I didn't make a backwards compatible change because the change is only in tests - the end user is not affected.

**Comment by benogle** [comment]
You're right, I thought I pulled that stuff.
