### ISSUE TITLE
Performance: tab-switching noticeably slower with autocomplete-plus enabled and lots of tabs open

### ISSUE THREAD

**Issue by gqshell** [atom-community/autocomplete-plus#247]
it seems to be rebuilding the wordlist everytime I switch tabs - is there a way to disable this?

Besides, I have the "Include Completions from All Buffers" setting enabled so all buffers should be using the same set of words anyways (?)

**Comment by joefitzgerald** [comment]
@gqshell, in the short term, please disable include completions from all buffers.

At issue is the following code:

* https://github.com/atom-community/autocomplete-plus/blob/f4173b31ba4a090e5e93149b08d5bb234c375794/lib/fuzzy-provider.coffee#L42
* https://github.com/atom-community/autocomplete-plus/blob/f4173b31ba4a090e5e93149b08d5bb234c375794/lib/fuzzy-provider.coffee#L126

We are not tracking all open editors, only the current one. Consequently, the entire wordlist is rebuilt every time you switch editors. That's not optimal, and causes performance issues if you have enough editors open and they are sufficiently large. 

FuzzyProvider has a short lifespan ahead of it. I'm not sure we will invest the time to fix this, but /cc @benogle to include this consideration in SymbolsProvider.

**Comment by benogle** [comment]
Yeah my implementation in symbol provider code isn't a whole lot better.
Though it is async and debounced which should help.
