### ISSUE TITLE
autocomplete.provider never called

### ISSUE THREAD

**Issue by steelbrain** [atom-community/autocomplete-plus#249]
Steps to reproduce:
 - Generate an empty package from Atom's Package Generator.
 - Add this to it's package.json file
```
  "providedServices": {
    "autocomplete.provider": {
      "versions": {
        "1.1.0": "provide"
      }
    }
  }
```
 - Add this to it's main cofffee main
```
  provide: ->
    console.log("Provide function called")
```
 - Reload Atom using CTRL+ALT+R

Et Viola It won't log "Providing function called" in the console.

**Comment by joefitzgerald** [comment]
1.0.1 isn't an API version. Use either 1.0.0 or 1.1.0.

**Comment by steelbrain** [comment]
The behaviour stays the same when using  `1.1.0` as version

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus proves it doesn't.

You may need to actually quit your atom window and relaunch it. I'm not sure how CTRL+R affects your testing. I know when I'm testing in a dev-mode window I close the window then reopen a new one (Cmd+shift+o).

Also note that 1.1.0 changes service.provider to service.providers (array).

**Comment by steelbrain** [comment]
I've tried restarting atom multiple times, and Yes it needs to return an array for v1.1.0 but how will it return something when it's never called :smiley: 
And can you please try the repro steps and tell me if it works for you.

**Comment by joefitzgerald** [comment]
You are opening atom in dev mode, right?

**Comment by steelbrain** [comment]
Yeah, It's in dev mode. It's v0.176.0 by the way.

**Comment by joefitzgerald** [comment]
Might want to upgrade to `0.177.0` :)

**Comment by steelbrain** [comment]
And yes, Upgrading fixed it. Thanks!
