### ISSUE TITLE
Can't change autocomplete-plus:select-next in keymap

### ISSUE THREAD

**Issue by 23tux** [atom-community/autocomplete-plus#261]
Hi,

I'm trying to overwrite some behaviour in my keymap.cson. But when I add this code, it has no effect:

```cson
'atom-text-editor:not(mini) .autocomplete-plus.autocomplete-suggestion-list':
  'tab': 'autocomplete-plus:select-next'
  'enter': 'autocomplete-plus:confirm'
  'up': 'unset!'
  'down': 'unset!'
```

I want to navigate through the suggestion list via `tab` and confirm them via `enter`. Can someone explain, why this isn't working? The example is from the readme.

**Comment by joefitzgerald** [comment]
@park9140 could the change you made last night change the selector that needs to be used for keybindings? If so, we need a :abc: docs update.

**Comment by park9140** [comment]
@joefitzgerald, not anymore.  The fix @benogle put in to remove the hidden input and allow IME input mode to work did however.

@23tux, you need to switch to using `atom-text-editor.autocomplete-active` as your selector.

**Comment by 23tux** [comment]
@park9140 When I change it to `atom-text-editor.autocomplete-active` then every enter triggers an autocomplete, not only when the suggestion window is active. Where do I look to see what selector it is?

**Comment by joefitzgerald** [comment]
I've observed this also.

**Comment by joefitzgerald** [comment]
@park9140 it appears that with the move away from the hidden input, we've broken the ability to use keymaps to redefine the bindings. This is why we backed away from it last time, also.

When this behavior exhibits itself, confirm seems to always get called on the last-confirmed item. I think we need to clear our the selected item so that this doesn't happen.

**Comment by joefitzgerald** [comment]
I found an easy way to prevent multiple-confirmation - but I'm not aware of how I allow enter to continue to service the editor once the suggestion list isn't active...

**Comment by joefitzgerald** [comment]
We're not removing `autocomplete-active` when the suggestion list is hidden:

`<atom-text-editor class="editor autocomplete-active" tabindex="-1" callattachhooks="true" data-grammar="source gfm" data-encoding="utf8"><div class="underlayer"><div is="wrap-guide" class="wrap-guide" style="left: 800px; display: block;"></div></div><div class="overlayer"></div></atom-text-editor>`

**Comment by joefitzgerald** [comment]
Yep, that fixed it.
