### ISSUE TITLE
Issues navigating the suggestion menu

### ISSUE THREAD

**Issue by lcosmin** [atom-community/autocomplete-plus#265]
I'm on OS X,  `atom 0.179.0`, `go-plus 3.2.2` and `autocomplete-plus 2.1.6`. 

I've configured autocomplete-plus to use `up` and `down` for navigating the suggestion list;  two issues I've noticed: `ctrl-p` and `ctrl-n` work (properly!) even though the setting says `up, down`  and using the arrows is buggy, the suggestion list closes on the first keypress (up or down) and usually works ok after I type a few more chars (from the text I want completed).

**Comment by joefitzgerald** [comment]
Do you have anything in your keymap?

**Comment by lcosmin** [comment]
Nothing customized in my keymap (everything is commented in `keymap.cson`)
I noticed something using the "Key Binding Resolver", not sure if useful/relevant:  when the autocompletion popup closes on pressing `down` (or `up`), i see two events (?): 
```
core:move-down                body                                  /Applications/...../darwin.json
native!                       body.native-key-bindings              /Applications/....../base.json
```

but when the popup is working properly, I see three:


```
autcomplete-plus:select-next atom-text-editor.autocomplete-active   atom-text-editor.autocomplete-active 
core:move-down                body                                  /Applications/...../darwin.json
native!                       body.native-key-bindings              /Applications/....../base.json
```

**Comment by hachre** [comment]
I've got the same problem on OS X. For me up/down just always moves the cursor in the editor instead of allowing me to choose something from the menu. I haven't gotten it to work once. My keymap file is empty. Recent versions of the same packages as mentioned in the post above. If you need any more info let me know.

**Comment by tststs** [comment]
+1

To reproduce this:
* type till there is only one suggestion left in the suggestion-list
* use backspace till the suggestion-list populates with > 1 items again
* using up/down now doesn't select the next/previous item, instead it loses focus, hides and the cursor is moved to next/previous line in the editor

**Comment by benogle** [comment]
I _have_ seen this before, but I am not able to reproduce with your steps, or anything else right now. I can get the inverse, though: filter down to one item, then the up/down keys do not move the cursor.

**Comment by benogle** [comment]
And I take all of that back. The key is that the first time it pops up, it must have only one suggestion.

Thanks for the steps @tststs
