### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gponsu** [atom-community/autocomplete-plus#266]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:64:11)
ProviderManager.module.exports.ProviderManager.consumeApi (/home/vicente/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:110:28)
```

**Comment by joefitzgerald** [comment]
This is already fixed. Please update your packages, and make sure you are running the latest version of packages and atom itself before logging issues. Thanks!
