### ISSUE TITLE
:: breaks autocomplete 

### ISSUE THREAD

**Issue by a-moses** [atom-community/autocomplete-plus#274]
:: break the autocomplete prosses

for example  PHP 5.4 and up :

Closure::bind

when type double '::' the autocomplete brack .

please make :: trigger autocomplate 

sources:
(http://php.net/manual/en/closure.bind.php)

**Comment by benogle** [comment]
Are you using a php provider? Or are you talking about the built-in provider?

The built in provider does not understand php, so it will not trigger on `::` like a specific php provider would.

**Comment by benogle** [comment]
Closing as the PHP provider can handle the `::` case. We will not be triggering on it in the default provider.
