### ISSUE TITLE
Enter key no longer chooses selection in 2.2.0

### ISSUE THREAD

**Issue by lombardi-gux** [atom-community/autocomplete-plus#277]
I had set autocomplete plus to complete with "enter" in the settings screen.  It was working fine, but I just updated to 2.2.0 and now it does not complete:

![autocomplete](https://cloud.githubusercontent.com/assets/7459986/6329355/91554040-bb3d-11e4-951b-9511093e8abd.gif)

Atom .182

**Comment by benogle** [comment]
Is this still a problem? Can you screenshot the keybinding resolver when pressing enter?

**Comment by smerchek** [comment]
I am also experiencing this problem (with version 2.3.0). What do you mean by screenshotting the keybinding resolver? I'm pretty new to Atom and haven't done much troubleshooting, but would be happy to help.

**Comment by benogle** [comment]
Interesting. I wonder if settings got messed up after one of the updates.

You can get the keybinding resolver via `cmd-.`. It tells you what command was called when you press a key combo.

@lombardi-gux Maybe try `tab`?

**Comment by xpol** [comment]
When auto complete list opens, all I need is `enter` for `core:confirm` and `tab` for `snippets:next-tab-stop`.

But currently `enter` does insert newline and `tab` is `core:confirm`.

**Comment by xpol** [comment]
Here is the key bind resolver:

![image](https://cloud.githubusercontent.com/assets/20248/6610645/28478d5c-c89d-11e4-95ee-fbe9cd68dbd2.png)

**Comment by xpol** [comment]
I have find solutions in autocomplete+ settings:

select `enter` in `Keymap For Confirming A Suggestion`.

**Comment by benogle** [comment]
Closing as this seems to be a non-problem anymore
