### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by XzK** [atom-community/autocomplete-plus#278]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:54:11)
Object.activate (/home/maniac/.atom/packages/autocomplete-plus/lib/autocomplete.coffee:31:31)
```

**Comment by joefitzgerald** [comment]
You must be using an ancient version of the package. Please update atom and your packages and restart.
