### ISSUE TITLE
Display snippets of documentation alongside selected autocomplete item

### ISSUE THREAD

**Issue by D-side** [atom-community/autocomplete-plus#279]
### Feature request

Some providers (namely, Haxe compiler, but pretty sure others exist) can be configured to output documentation snippets along with suggestions. I suggest making a widget near the suggestion list that displays documentation for the selected item. Something like this is implemented in Visual Studio:

![Screenshot](http://www.codeproject.com/KB/mobile/460836/Untitled.png)

This can probably be added as an optional element of suggestion object, that can contain HTML-formatted text. For instance, Haxe outputs markdown, which can be crunched with `marked` and sent back as HTML. The problem is, it can be quite large, so it should be scrollable.

**Comment by benogle** [comment]
I really like the way xcode does it: 

![method](https://cloud.githubusercontent.com/assets/69169/5948007/4dea40a4-a6f6-11e4-818e-cee6e3332d07.png)

So rather than an extra popup, we could just have a widget at the bottom of suggestion box.

**Comment by D-side** [comment]
I'll be fine with either one :) Never worked with XCode before, but looks okay.

Larger documentation snippets probably shouldn't be autocomplete's job. A single line of docs will suffice most of the time.

Maybe an optional `url` field can be added to suggestions for opening full docs in the preferred browser (maybe even with [Atom's own browser capabilities](https://atom.io/packages/atom-browser-webview), once they mature). Fully implementing it in providers will be a pain, I imagine, but the benefits are clear.

**Comment by tinloaf** [comment]
@benogle Are you OK with either of this? I'd like this feature, too, and I'm thinking about taking a look at the autocomplete-plus codebase and see if I can get it done.

**Comment by benogle** [comment]
@tinloaf I'd like it the way xcode does it, at the bottom of the suggestion list. You'll need to accept a new parameter from each suggestion, maybe called `description`. So the providers would return

```coffee
suggestion = 
  text: 'someMethod()'
  description: 'Does things and stuff. This could be [markdown](http://daringfireball.net/projects/markdown/syntax)'
```

The description will likely need to supoprt linking. Markdown may be a nice thing here. Or we could use the convention of the other params, and call it `descriptionHTML` then support raw HTML. Though, I want to limit power here, and just encourage text with ability to link.

**Comment by joefitzgerald** [comment]
Would there be some limit to the size of description, or would the UI show a truncated portion (allowing optional expansion on hover or click)?

**Comment by benogle** [comment]
Yeah truncated one liner, allowing for scrolling side to side, similar to the tabs when you have too many tabs.

**Comment by joefitzgerald** [comment]
Scrolling ala tabs seems awkward. Why not have a [...] if more exists and allow a hover to show a much larger overlay with the documentation? Or allow the [...] to expand the documentation section downwards...

**Comment by benogle** [comment]
I would like to try a one liner initially before making another popup. If it sucks or providers all really need the popup, then we can do a popup. IMO, start simple, and iterate.

**Comment by joefitzgerald** [comment]
:+1:.

**Comment by tinloaf** [comment]
How about this? I'm not sure if the text should visually be more separated from the list.. Also, I currently set a manual max-width for the box. I'm not sure it that's the best way to do it...


![2015-04-01-214559_1920x1200_scrot](https://cloud.githubusercontent.com/assets/442687/6950148/1cb3cd12-d8b9-11e4-8a9d-07ae3c910177.png)
![2015-04-01-214859_1920x1200_scrot](https://cloud.githubusercontent.com/assets/442687/6950151/2262ec34-d8b9-11e4-9fb8-a7dff8e726ea.png)

**Comment by benogle** [comment]
Make a PR. I think a maxwidth on the box is reasonable. #334 also adds a max-width, and truncates the word when too long.

**Comment by joefitzgerald** [comment]
I think this was fixed by @benogle - there is now a way to specify doc strings in suggestions and they are displayed in the suggestion list.

**Comment by jkabrg** [comment]
@joefitzgerald Your comment doesn't say how to do it.
