### ISSUE TITLE
New HTML and CSS providers

### ISSUE THREAD

**Issue by kevinsawicki** [atom-community/autocomplete-plus#284]
Just wanted to give a heads up that today I published two new autocomplete-plus providers, one for CSS and one for HTML. They both use the 1.1 provider API.

### CSS

This one does property names and values in CSS, SCSS, and Less files.

https://github.com/atom/autocomplete-css

![](https://cloud.githubusercontent.com/assets/671378/6357910/b9ecbe7c-bc1c-11e4-89b1-033e626c891f.gif)

### HTML

This one does tag names, attribute names, and attribute values in HTML files.

https://github.com/atom/autocomplete-html

![](https://cloud.githubusercontent.com/assets/671378/6364047/d826b490-bc55-11e4-90a8-01d23ea642d9.gif)

I updated the [providers wiki page](https://github.com/atom-community/autocomplete-plus/wiki/Autocomplete-Providers) to include them. Just wanted to also mention that [the docs](https://github.com/atom-community/autocomplete-plus/wiki/Provider-API) were great :+1:

**Comment by joefitzgerald** [comment]
Awesome! Great to see this. Thanks for the heads up @kevinsawicki

**Comment by kevinsawicki** [comment]
Closing this out.
