### ISSUE TITLE
bad performance with language-php package

### ISSUE THREAD

**Issue by Platzer** [atom-community/autocomplete-plus#288]
i had some troubles with autocompletion in php files. like in #181 i got all possible php completions.
so i removed all "completions" in [atom / language-php] (https://github.com/atom/language-php/blob/master/settings/language-php.cson), about 3000 and now its working great...

atom 0.184
autocomplete-plus 2.2.0

**Comment by joefitzgerald** [comment]
@benogle performance related to maxItems?

**Comment by benogle** [comment]
yeah may be. We can set it low for now

**Comment by robneu** [comment]
+1 also having this issue. Using the Fuzzy provider it's almost totally unusable on PHP files. Performance is better using Symbol, but matching is almost nonexistent.

**Comment by rezzz-dev** [comment]
+1 I'd say so -- when not in PHP files it's better.  However it's still a little sluggish.  But in PHP files it's virtually unusable

**Comment by benogle** [comment]
Can you guys upgrade to 2.5.0 and let me know if it is faster?

**Comment by robneu** [comment]
Just updated. It's much faster within PHP files with only the PHP language running. It's still extremely slow when using the [WordPress API](https://github.com/azizur/atom-wordpress-api), but that seems more like an issue with that package than autocomplete.

**Comment by joefitzgerald** [comment]
Closing this in deference to https://github.com/azizur/atom-wordpress-api/issues/6.

**Comment by rezzz-dev** [comment]
I would agree with @robneu in that when I disable the WordPress API plugin, it's much better.  Thanks for the fix.

**Comment by arielnoname** [comment]
+1 @rezzz-dev
