### ISSUE TITLE
buildWordList is noticeably slow when saving

### ISSUE THREAD

**Issue by dmnd** [atom-community/autocomplete-plus#289]
I noticed that something was synchronously executing upon save. Profiling shows that it's `buildWordList`:

![image](https://cloud.githubusercontent.com/assets/4427/6405067/d40063dc-bdd3-11e4-8da6-b13592963e01.png)

I noticed you're using `_.unique`. Perhaps a `Set` would be quicker? Also, is there a reason this needs to happen on the main thread?

**Comment by joefitzgerald** [comment]
FuzzyProvider is deprecated and will be replaced entirely in some future release of `autocomplete-plus`. Consequently, this will not be fixed.

**Comment by benogle** [comment]
Actually, I want to surface fix it as fuzzy provider might be the default for a bit when autocomplete gets into core. My plan was to debounce the word list generation. I think that could lighten the load.
