### ISSUE TITLE
Long undefined list on backspace removing all previously typed characters

### ISSUE THREAD

**Issue by orderedlist** [atom-community/autocomplete-plus#295]
I noticed this happens in CSS/Less files, didn't notice it in Coffee files
- Type a few characters, get a list
- Backspace to remove all characters
- Get something like this

![screen shot 2015-02-28 at 10 12 25 am](https://cloud.githubusercontent.com/assets/1680/6426621/991b6536-bf32-11e4-879d-85174bb64ca3.png)

**Comment by neurobashing** [comment]
It happens in Python, and with a dark theme.

**Comment by lierdakil** [comment]
Probably related to #298, #299

**Comment by benogle** [comment]
Sorry about this, it's out in 2.3.1.
