### ISSUE TITLE
Problem rendering suggestions when giving "snippet" without "text"

### ISSUE THREAD

**Issue by jeremyfa** [atom-community/autocomplete-plus#302]
When I set a ``snippet`` attribute to some suggestions, without setting a ``text`` attribute (as stated in the provider docs), only one (or some) suggestions are being displayed:

![capture d ecran 2015-03-04 a 11 52 18](https://cloud.githubusercontent.com/assets/164094/6482364/68ecebec-c265-11e4-80e7-710390f06285.png)

If I add a ``text`` attribute in addition to the ``snippet`` one, the problem doesn't occur.

These are the suggestions I am providing in this case:

```json
[
    {
        "label": "mylabel",
        "snippet": "_check(${1:arg1}, ${2:arg2})"
    },
    {
        "label": "mylabel",
        "snippet": "assets_loaded(${1:arg1}, ${2:arg2})"
    },
    {
        "label": "mylabel",
        "snippet": "config(${1:arg1}, ${2:arg2})"
    },
    {
        "label": "mylabel",
        "snippet": "create_ship(${1:arg1}, ${2:arg2})"
    },
    ...
]
```

**Comment by benogle** [comment]
Thanks a bunch for reporting this
