### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by swest** [atom-community/autocomplete-plus#305]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
ProviderManager.module.exports.ProviderManager.consumeApi (/Users/username/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:110:28)
```

Atom 0.186.0
autocomplete-plus 2.4.0

**Comment by joefitzgerald** [comment]
Guessing you got this after you upgraded autocomplete-plus but prior to restarting atom. If you haven't already, restart atom. Deprecation cop does not re-evaluate deprecations until after a restart apparently.
