### ISSUE TITLE
Repeat first character on completion.

### ISSUE THREAD

**Issue by Abukamel** [atom-community/autocomplete-plus#307]
* Issue: repeating first character when auto completing the first word on the line.
* Reproducing:  [Youtube Video](https://www.youtube.com/watch?v=ISAOQ0hygBo&feature=youtu.be)
* Atom version: 0.186.0
* Package version: 2.4.1

**Comment by joefitzgerald** [comment]
This could be (and most likely is) an issue with the provider you're using. What packages do you have installed?

**Comment by Abukamel** [comment]
Do you want me to list all installed packages on manjaro linux?


  [image: photo]
*Ahmed Kamel*
Associate System Administration Manager, Arabhosters
 m:+201140773046 | e:a.kamel@arabhosters.com |
w:http://arabhosters.com | a: Head
Office: 26 Ali Amin St. Nasr City, Cairo Egypt
 <http://eg.linkedin.com/pub/ahmed-kamel/>
  <https://www.linkedin.com/profile/view?id=130626886>
"Success is to be measured not so much by the position that one has reached
in life... as by the obstacles which he has overcome while trying to
succe...
<http://www.quotesdaddy.com/quote/98613/booker-t-washington/success-is-to-be-measured-not-so-much-by-the-position>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
 Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

[image: photo]
*Ahmed Kamel*
Linux System Engineer, Odesk
m:+201140773046 | e:k.tricky@gmail.com
<http://eg.linkedin.com/pub/ahmed-kamel/>  <http://twitter.com/Abukameleo>
<https://twitter.com/Abukameleo>
<https://www.linkedin.com/profile/view?id=130626886>
"Don't wait until everything is just right. It will never be perfect. There
will always be challenges, obstacles and less than perfect conditions. So
...
<http://www.quotesdaddy.com/quote/1041647/mark-victor-hansen/dont-wait-until-everything-is-just-right-it-will-never>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by joefitzgerald** [comment]
> Do you want me to list all installed packages on manjaro linux?

No I'm referring to `atom` packages. Run `apm list`, and paste the output.

**Comment by Abukamel** [comment]
Built-in Atom packages (85)
├── archive-view@0.50.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.47.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.23.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.37.0
├── dev-live-reload@0.42.0
├── encoding-selector@0.18.0
├── exception-reporting@0.24.0
├── feedback@0.34.0
├── find-and-replace@0.159.0
├── fuzzy-finder@0.70.0
├── git-diff@0.54.0
├── go-to-line@0.30.0
├── grammar-selector@0.45.0
├── image-view@0.49.0
├── incompatible-packages@0.22.0
├── keybinding-resolver@0.29.0
├── language-c@0.41.0
├── language-clojure@0.13.0
├── language-coffee-script@0.39.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.67.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.29.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.61.0
├── language-json@0.12.0
├── language-less@0.25.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.13.0
├── language-php@0.21.0
├── language-property-list@0.8.0
├── language-python@0.32.0
├── language-ruby@0.49.0
├── language-ruby-on-rails@0.20.0
├── language-sass@0.36.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.139.0
├── metrics@0.45.0
├── notifications@0.31.0
├── one-dark-syntax@0.3.0
├── one-dark-ui@0.5.0
├── one-light-syntax@0.4.0
├── one-light-ui@0.4.0
├── open-on-github@0.34.0
├── package-generator@0.38.0
├── release-notes@0.51.0
├── settings-view@0.184.0
├── snippets@0.80.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.55.0
├── status-bar@0.63.0
├── styleguide@0.44.0
├── symbols-view@0.88.0
├── tabs@0.67.0
├── timecop@0.31.0
├── tree-view@0.164.0
├── update-package-dependencies@0.9.0
├── welcome@0.25.0
├── whitespace@0.29.0
└── wrap-guide@0.31.0

/home/abukamel/.atom/packages (17)
├── atom-beautify@0.21.4
├── atom-jinja2@0.5.0
├── autocomplete-css@0.4.0
├── autocomplete-emojis@1.0.0
├── autocomplete-html@0.3.0
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.4.2
├── autocomplete-plus-jedi@0.0.8
├── autocomplete-snippets@1.0.1
├── ex-mode@0.3.0
├── language-salt@0.2.0
├── linter@0.12.0
├── linter-flake8@1.3.0
├── minimap@4.5.0
├── script@2.18.0
├── vim-mode@0.37.0
└── vim-surround@0.4.2



  [image: photo]
*Ahmed Kamel*
Associate System Administration Manager, Arabhosters
 m:+201140773046 | e:a.kamel@arabhosters.com |
w:http://arabhosters.com | a: Head
Office: 26 Ali Amin St. Nasr City, Cairo Egypt
 <http://eg.linkedin.com/pub/ahmed-kamel/>
  <https://www.linkedin.com/profile/view?id=130626886>
"Success is to be measured not so much by the position that one has reached
in life... as by the obstacles which he has overcome while trying to
succe...
<http://www.quotesdaddy.com/quote/98613/booker-t-washington/success-is-to-be-measured-not-so-much-by-the-position>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
 Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

[image: photo]
*Ahmed Kamel*
Linux System Engineer, Odesk
m:+201140773046 | e:k.tricky@gmail.com
<http://eg.linkedin.com/pub/ahmed-kamel/>  <http://twitter.com/Abukameleo>
<https://twitter.com/Abukameleo>
<https://www.linkedin.com/profile/view?id=130626886>
"Don't wait until everything is just right. It will never be perfect. There
will always be challenges, obstacles and less than perfect conditions. So
...
<http://www.quotesdaddy.com/quote/1041647/mark-victor-hansen/dont-wait-until-everything-is-just-right-it-will-never>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by joefitzgerald** [comment]
I believe your issue is with this code: https://github.com/fallenhitokiri/autocomplete-plus-jedi/blob/71fa5f6415271e4fc4d4f0dfa720b8d288867bb6/lib/jedi-provider.coffee#L46-L48

Suggest you create an issue at https://github.com/fallenhitokiri/autocomplete-plus-jedi/issues/new

**Comment by Abukamel** [comment]
Thanks, i just did.
