### ISSUE TITLE
Snippets word display needs html escaping

### ISSUE THREAD

**Issue by basarat** [atom-community/autocomplete-plus#309]
Sample 
![image](https://cloud.githubusercontent.com/assets/874898/6544946/fa0c0690-c5bb-11e4-993b-4c63fc2f6cd9.png)

for : `(${1:parameter}) => { ${2:return true;} }`

**Comment by benogle** [comment]
Is this in the latest version of autocomplete-plus? This should be fixed.

**Comment by basarat** [comment]
Was the latest *then*. Is fixed in the current version :heart: 

![image](https://cloud.githubusercontent.com/assets/874898/6648960/1855d00e-ca35-11e4-8fbd-1f365b4f308b.png)
