### ISSUE TITLE
onDidInsertSuggestion should include all the stuff that was there in the original `getSuggestions` options bag

### ISSUE THREAD

**Issue by basarat** [atom-community/autocomplete-plus#310]
We used properties of `options` e.g. the `scope` to determine what we did on `onDidConfirm`. The `options` is no longer available on `onDidInsertSuggestion` as far as I can tell from wiki https://github.com/atom-community/autocomplete-plus/wiki/Provider-API

refs : https://github.com/TypeStrong/atom-typescript/issues/174

**Comment by basarat** [comment]
Also we lose the context *surrounding* the suggestion e.g. the precomputed results relevant to the suggestion (in our case a filename). 

So I guess the new pattern is to add stuff to `suggestion` that you will need in `onDidInsertSuggestion`

**Comment by basarat** [comment]
using suggestion as something to pass around it is then :heart:

**Comment by benogle** [comment]
What bit specifically do you need from the options? What are you using it for?

**Comment by basarat** [comment]
> What bit specifically do you need from the options

the `scope`. 

> What are you using it for

Using it to determine if we needed to do additional stuff `onDidConfirm` e.g. more editor text mutation. 

You can ignore this issue now as the workaround was to simply pass this stuff into suggestion and pull it out on onDidInsertSuggestion :+1:
