### ISSUE TITLE
Fuzzy provider not always picking up new symbols

### ISSUE THREAD

**Issue by nathansobo** [atom-community/autocomplete-plus#330]
In this example, I'm unable to trigger a manual completion at the cursor position despite the presence of a word with that prefix in the buffer.

![screen shot 2015-03-21 at 4 35 14 am](https://cloud.githubusercontent.com/assets/1789/6764701/01d70916-cf84-11e4-8c5f-92f739c847e5.png)

If you give me an expression to access the provider's state I can try to gather info next time this happens. From cursory inspection in the dev tools it seems like they might be stored in a private local variable? Or I'm just missing the property.

**Comment by benogle** [comment]
Here is how you get the word list:

```js
ac = atom.packages.getActivePackage('autocomplete-plus')
acm = ac.mainModule.getAutocompleteManager()
fp = acm.providerManager.fuzzyProvider
fp.wordList
```

Do you remember when you typed `symmetrical`?  I assume you typed the function call, did not save, then went to type the definition. True? Do you remember doing anything in between typing the definition and trying to type the function name again?

The wordlist will be regenerated on save, so saving is a way to fix this while working.

**Comment by nathansobo** [comment]
@benogle I think you're probably right that I didn't save. How hard would it be to make that work. I feel like only rebuilding the word list on save is a bit surprising... it surprised me at least and caused me frustration.

**Comment by benogle** [comment]
> How hard would it be to make that work

Not sure I follow. Make what work? Right now it should add new words on each edit. It wipes and regens on save, but will add new words as you are typing.

**Comment by nathansobo** [comment]
@benogle Oh so I did indeed encounter a bug then?

**Comment by benogle** [comment]
Yeah, are words not added as you type?

**Comment by nathansobo** [comment]
Yeah, check it out:

![autocomplete](https://cloud.githubusercontent.com/assets/1789/6810341/ad8d0a6e-d225-11e4-99f1-bb07a166de2f.gif)

**Comment by benogle** [comment]
Looks like if you type a non-word char, it will cache the new word. Newlines mess it up, currently. So `testing` then `space` will save the word.
