### ISSUE TITLE
Always strict match on current prefix when manual completion is toggled

### ISSUE THREAD

**Issue by nathansobo** [atom-community/autocomplete-plus#332]
In many cases, I have a unique prefix, but the fuzzy match is pulling in all this noise. If we strict matched the prefix I could complete immediately. @benogle I can see why you could think autocomplete was terrible and I could think it was fine, because the manual use case gives you more discretion on the prefix for a strict match.

I actually think we should apply this in the case of auto-popup as well. If you hit ctrl-space when the menu is visible, it sets the strict filter to the current prefix.

![screenshot_2015-03-21_05_27_52](https://cloud.githubusercontent.com/assets/1789/6764865/7a670ec4-cf8b-11e4-92c7-a82ae4a5953d.png)

**Comment by benogle** [comment]
Doing this generically is problematic. Let's say you had a clang provider installed:

```coffee
specialProvider =
  selector: '*'
  getSuggestions: ({prefix}) ->
    replacementPrefix = "self #{prefix}"
    [{text: '[self abcOk]', replacementPrefix}, {text: '[self aabcOk]', replacementPrefix}]
```

You typed the following with your cursor at the end:

```
self omg
```

This is impossible to match in a generic way. The point is that the provider can return anything it wants. 

If you typed something a little more reasonable like:

```
self abc
```

None of the suggestions that come back from the provider (e.g. `[self abcOk]`) strict match the prefix generated by autocomplete (`abc`) _or_ the `replacementPrefix`  (`self abc`). One way maybe around this is to do an `indexOf` on each suggestion with the replacementPrefix. So basically: 

```coffee
if '[self abcOk]'.indexOf('self abc') > -1 
  console.log 'strict match'
```

But that seems pretty shaky. 

Other options

1. blindly test `suggestion.text.indexOf(prefix) is 0` with the autocomplete generated prefix (`abc`) on the suggestions. Any providers who dont use the built in prefix are SOL
2. Store the replacementPrefix that comes back for each provider, then filter each providers suggestions based on the method in (1). Again, some providers, like the clang one outlined above would not support this, and would be always filtered out of manual activation.
3. Support this in the default provider. We'd need to pass the manual activation information to `getSuggestions`.

Overall, this is not very cut and dry.

**Comment by benogle** [comment]
My vote, BTW, is for option number 3 -- just support it in the default providers. Though adding more information to `getSuggestions` sucks.

**Comment by nathansobo** [comment]
@benogle Could you bail out of the strict match if the `replacementPrefix` is not a case-insensitive prefix of the suggestion?

**Comment by benogle** [comment]
Yeah, that might work. That should make complicated providers opt-out of this.

**Comment by nathansobo** [comment]
:heart;
