### ISSUE TITLE
Allow multiple classes for suggestions

### ISSUE THREAD

**Issue by tinloaf** [atom-community/autocomplete-plus#342]
Hi,

could you please add the possibility to have a list of classes for the className attribute of the suggestions? I'd like to style a suggestion for a method in the same font as my syntax theme set for fonts. This could be achieved setting the classes "entity name method", but I don't think it's possible to do this with just one class.

**Comment by benogle** [comment]
Can you elaborate on what you want to do? The word font should already match the editor font:

![screen shot 2015-03-30 at 10 30 20 am](https://cloud.githubusercontent.com/assets/69169/6902342/1ffb67c0-d6c8-11e4-915c-79ba15e4bd68.png)

I think handling multiple classes is reasonable, but I'd like to understand whats tripping you up.

**Comment by joefitzgerald** [comment]
@benogle My interpretation is that @tinloaf would like to style each suggestion list item with the actual font the suggestion pertains to. So he would like to have one or many per-suggestion class(es) that can be used to style the suggestions accordingly.

**Comment by tinloaf** [comment]
Yes, exactly. For example: If a suggestion is a function (like addToken in your example), I'd like it to look like a function in the editor (in your example: removeInstance). In your theme, that would mean "blue".

Now, if you look at the editor window, "removeInstace" should have somethink like three classes, and they should look like "entity name method" or so. Therefore, I'd like to add the classes "entity name method" to the suggestions (that suggest functions), too. Same for variables, keywords, ...

Did it become clearer?

**Comment by benogle** [comment]
Yes it's clearer, thanks for the explanation. Near the 1.0, the syntax themes will not be loaded into the main context, so applying the classes would not work long term. I'd like to get all providers to adhere to some conventions regarding colorizing to match the syntax. I'd like the colorization to be applied to an icon next to the match. Take a look at this PR: https://github.com/atom-community/autocomplete-plus/pull/334 specifically this:

![63578990-d182-11e4-988f-2fc4ed3cbccb](https://cloud.githubusercontent.com/assets/69169/6908757/96c966e6-d6f4-11e4-9333-be5b4da37df7.png)

The changes in that PR will give you as a provider author simple tools to match the syntax theme. You'd just specify a suggestion type, like `function` or `class

**Comment by tinloaf** [comment]
That looks great! Are the colors taken from the syntax theme? Would it be possible to add an option to switch between coloring the indicator on the left an coloring the text with it?

**Comment by benogle** [comment]
We tried the colors on the text, and it does not look good. It looks really adhoc and messy. Also, some suggestion types do not have a syntax color counter-part. Snippets would be colored with green text, but in reality, they are not green in the code. We felt like the colored icons were the best bet.

**Comment by tinloaf** [comment]
This seems obsolete with the left icons.
