### ISSUE TITLE
First proposed match always appear next to current line.

### ISSUE THREAD

**Issue by romgrk** [atom-community/autocomplete-plus#346]
- The first proposed match is always shown at the top of the list.
- When the cursor is low in the screen, the list appears above current line.

Therefore, the first proposed match is the furthest away from the eye.

Request: inverse display when the popup list is shown above the current line.

**Comment by benogle** [comment]
I'd rather not change the sort order. I think it would be more confusing to change the sort order than to have it far away form the cursor.

**Comment by joefitzgerald** [comment]
I agree with @benogle.
