### ISSUE TITLE
Make confirmation of suggestion configurable

### ISSUE THREAD

**Issue by 23tux** [atom-community/autocomplete-plus#354]
Hi,

I found it very annoying, that you have to use enter or tab (or both) for confirming a suggestion. I tried to change it in my keymaps, but nothing worked. So I just commented out these two lines in `suggestion-list.coffee`:

```
    # keys['tab'] = 'autocomplete-plus:confirm' if completionKey.indexOf('tab') > -1
    # keys['enter'] = 'autocomplete-plus:confirm' if completionKey.indexOf('enter') > -1
```

And added my own confirmation key in my `keymap.cson`:

```
'atom-text-editor:not(mini).autocomplete-active':
  'cmd-shift-enter': 'autocomplete-plus:select-next'
  'cmd-enter': 'autocomplete-plus:confirm'
```

This works for now, but it would be really useful, to deactivate enter and tab.

**Comment by joefitzgerald** [comment]
@23tux https://github.com/atom-community/autocomplete-plus#usage provides the instructions you are looking for. You do not need to comment out the code you commented.

**Comment by 23tux** [comment]
For, this doesn't work. I tried this in my `keymap.cson`:

```
'atom-text-editor:not(mini).autocomplete-active':
  'cmd-shift-enter': 'autocomplete-plus:select-next'
  'cmd-enter': 'autocomplete-plus:confirm'
  'tab': 'unset!'
  'enter': 'unset!'
  'up': 'unset!'
  'down': 'unset!'
  'ctrl-p': 'unset!'
  'ctrl-n': 'unset!'
```

When I start typing, of course I can use my custom `select-next` and `confirm` keybindings. But when the suggestion window is present, and I try to press enter, nothing happens. The expected result would be to insert a new line (normal behaviour).

Furthermore, when I try to press `tab` the current focus jumps to the footer `UTF-8` link, where you can change the encoding of your file. This is really really annoying (e.g. you are trying to use the autocomplete feature from the javascript package, where you can type `log` and press `tab` and then it becomes `console.log()`)

Does this only happen to me?

**Comment by 23tux** [comment]
Unfortunately, this still doesn't work, including the newest update. I'm on a Mac, don't know if this is helpful.
