### ISSUE TITLE
ProviderManager.module.exports.ProviderManager.registerProvider is deprecated.

### ISSUE THREAD

**Issue by rjazevedo** [atom-community/autocomplete-plus#357]
Autocomplete provider 'JediProvider(autocomplete-plus-python-jedi)'
contains an `id` property.
An `id` attribute on your provider is no longer necessary.
See https://github.com/atom-community/autocomplete-plus/wiki/Provider-API
```
ProviderManager.module.exports.ProviderManager.registerProvider (/Users/rodolfo/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:126:13)
registerProvider (/Users/rodolfo/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:1:0)
```

**Comment by benogle** [comment]
cc @tinloaf

**Comment by tinloaf** [comment]
Fixed in https://github.com/tinloaf/autocomplete-plus-python-jedi/commit/17c16e7e0334747ff5673827c7024fe898d9831d

Thanks for the hint!
