### ISSUE TITLE
Workspace.getEditors is deprecated.

### ISSUE THREAD

**Issue by Hokutosei** [atom-community/autocomplete-plus#361]
Use Workspace::getTextEditors instead
```
Workspace.getEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:368:7)
FuzzyProvider.module.exports.FuzzyProvider.buildWordList (/Users/soliva/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:141:31)
```

used the utility in atom, from deprecation cop.

**Comment by joefitzgerald** [comment]
Already fixed, in f8cac61. Duplicate of #350. Please update your version of autocomplete-plus and ensure you are running the latest version of atom.
