### ISSUE TITLE
Hide snippet (or $0) in suggestions

### ISSUE THREAD

**Issue by Peekmo** [atom-community/autocomplete-plus#375]
Hello,

Is there a way to hide the snippet, or the $0 in suggestions list ? It's not really nice to see the $0 at the end of every line.

E.G
![screenshot](http://i.imgur.com/v4OGe1T.png?raw=true)

Thank you for your answer,
Peekmo

**Comment by benogle** [comment]
What provider are you using? Likely an issue on their end.

**Comment by Peekmo** [comment]
It's my own provider, that build the snippet and I use $0 for the final tab (https://github.com/Peekmo/atom-autocomplete-php/blob/master/lib/php-abstract-provider.coffee#L15)
Perhaps may I have to use something else for the final tab ?

**Comment by AustP** [comment]
+1. @benogle Let me give you another example. All of the below cases complete to `abs($number)` while the first tab selects `$number` and the second tab places the cursor after the closing parenthesis. But the suggestion is including "snippet code".

- `snippet: 'abs(${0:$number})$1'` - suggests `abs($number)$1`
- `snippet: 'abs(${0:$number})${1}'` - suggests `abs($number)${1}`
- `snippet: 'abs(${0:$number})${1:}'` - suggests `abs($number)${1:}`

**Comment by benogle** [comment]
Makes sense, and seems reasonable.

**Comment by joefitzgerald** [comment]
@AustP I can confirm that this is not working as expected for you, and am working on a fix that also addresses an issue with escaped right braces (`}`) inside snippets. This requires a shift in approach, so I'll create a PR and reference back here for your feedback.
