### ISSUE TITLE
Move The Package Into Core / Upstream The Package

### ISSUE THREAD

**Issue by edubkendo** [atom-community/autocomplete-plus#38]
Would be really great if the provider API worked with both.

The worst thing that could happen is if the atom package implemented a different API.  Then authors would have to either choose one, or support both. Neither of those is a great option.

I don't know how this is architected internally, and maybe its difficult to upstream as its currently written. But if that isn't the case, would be great.

**Comment by joefitzgerald** [comment]
@benogle what are your plans on this topic? Is there a timeline / a list of outstanding items that must be completed / any pending questions from the Atom team?

**Comment by joefitzgerald** [comment]
Closing in deference to #351.
