### ISSUE TITLE
Autocomplete re-triggered immediately after confirming the selected suggestion

### ISSUE THREAD

**Issue by Peekmo** [atom-community/autocomplete-plus#382]
Hello,

As mentionned in this issue : https://github.com/atom-community/autocomplete-plus/pull/184 it seems that it's possible to re-trigger autocomplete just after confirming the selected suggestion. 
How can I do this please ?

Regards,
Peekmo

**Comment by joefitzgerald** [comment]
Take a look at autocomplete-paths.
