### ISSUE TITLE
As of latest (2.10.0) suggestions overflow

### ISSUE THREAD

**Issue by tylerFowler** [atom-community/autocomplete-plus#392]
I've noticed that right after I updated this morning to v2.10.0 that suggestions now overflow out of the box. I'm fairly certain this wasn't happening yesterday (pre-update) so it looks like an `overflow: hidden` rule is just missing somewhere.

**Comment by benogle** [comment]
Have you reloaded atom after the update? I did change where the overflow rules are targeting.

**Comment by tylerFowler** [comment]
Yes reloading did the trick, thanks!
