### ISSUE TITLE
Case mismatch disables tab completion

### ISSUE THREAD

**Issue by aaronkavlie-wf** [atom-community/autocomplete-plus#393]
Matches are highlighted in the autocomplete list even if case does not match. For example, `time.mil` and `time.Mil` both highlight the `Millisecond` constant from Go's `time` package.

However, pressing tab with input `mil` just dismisses the list of matches; only `Mil` auto-completes the suggestion.

Expected behavior is that the input always auto-completes to the highlighted match on a tab (or whatever is set as the "confirming a suggestion" key) press.

**Version:** 2.10.0
**Setup**: using to write Go code with *go-plus*

**Comment by benogle** [comment]
cc @joefitzgerald due to go-plus ref

**Comment by optimality** [comment]
I'm also suffering from this.  Let me know if I can help; it's quite frustrating.

**Comment by joefitzgerald** [comment]
Thanks for the report. Could you please open an issue at https://github.com/joefitzgerald/go-plus/issues/new?

**Comment by joefitzgerald** [comment]
Closing this in deference to https://github.com/joefitzgerald/go-plus/issues/185.
