### ISSUE TITLE
hint-hud has a wide offset from input

### ISSUE THREAD

**Issue by tralles** [atom-community/autocomplete-plus#394]
having os-x 10.10.3 and a doc located at the left side of my screen, the hint has an offset from current input …

![offset](https://cloud.githubusercontent.com/assets/992529/7168455/d927aa0e-e3bd-11e4-82a6-0df3b2342a5d.png)

**Comment by benogle** [comment]
What version of autocomplete-plus? Can you reload atom and does the issue persist?

**Comment by tfausak** [comment]
I also experience this problem. I'm using Atom 0.192.0 on OS X 10.10.3 with autocomplete-plus 2.10.0 and autocomplete 0.44.0. I think the minimap plugin (version 4.7.6) is to blame. Check out atom-minimap/minimap#317.

**Comment by joefitzgerald** [comment]
@benogle This might be related to #399.

**Comment by joefitzgerald** [comment]
@tralles Do you have the minimap package installed and activated? See also #412, #399, https://github.com/atom-minimap/minimap/issues/317.
