### ISSUE TITLE
wrong suggestion when the word's first letter is Uppercase 

### ISSUE THREAD

**Issue by haikyuu** [atom-community/autocomplete-plus#395]
When the word's first letter is Uppercase and both lowercase and uppercase words are present, it suggests the lowercase word and *vice versa*
![atom autoc](https://cloud.githubusercontent.com/assets/8558836/7180793/dc5e85c4-e43c-11e4-8704-1ee6879bcfa0.png)

**Comment by benogle** [comment]
This is because the `FuzzyProvider` doesnt show exact matches. You should switch to the `Symbol` provider in the settings (the last setting at the bottom). It should generally be better overall.

**Comment by benogle** [comment]
Closing this as a wontfix as the symbol provider solves it.

**Comment by haikyuu** [comment]
Thanks, i tried that and restarted atom but it still occurs

**Comment by benogle** [comment]
Same exact result? This is what I see:

![screen shot 2015-04-17 at 11 43 34 am](https://cloud.githubusercontent.com/assets/69169/7208708/802baf0a-e4f7-11e4-9efb-3c678e746b1f.png)

**Comment by haikyuu** [comment]
I rebooted and it works now :) thanks
