### ISSUE TITLE
Settings missing?

### ISSUE THREAD

**Issue by cfjedimaster** [atom-community/autocomplete-plus#398]
On the web site, you mention enabling Show Suggestions On Keystroke. However, when I go to settings I do not see this.

**Comment by cfjedimaster** [comment]
jeeze - im blind. i didnt know plugins had their own settings button. sorry.

**Comment by benogle** [comment]
Yar. Probably not the most intuitive place for them.

**Comment by cfjedimaster** [comment]
Well, I'm new to Atom too.

On Fri, Apr 17, 2015 at 1:06 PM, Ben Ogle <notifications@github.com> wrote:

> Yar. Probably not the most intuitive place for them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom-community/autocomplete-plus/issues/398#issuecomment-94041385>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
