### ISSUE TITLE
Fix flaky spec

### ISSUE THREAD

**Issue by benogle** [atom-community/autocomplete-plus#399]
Often the build fails because of this:

```
Autocomplete Manager
  when an external provider is registered
    when autocomplete-plus.suggestionListFollows is 'Word'
      it keeps the suggestion list planted at the beginning of the prefix when typing
        Expected '138px' to be '61px'.
          at [object Object].<anonymous> (/Users/travis/build/atom-community/autocomplete-plus/spec/autocomplete-manager-integration-spec.coffee:502:45)
          at Immediate._onImmediate (/Users/travis/build/atom-community/autocomplete-plus/spec/spec-helper.coffee:23:9)
```

**Comment by joefitzgerald** [comment]
By the way, @benogle the AppVeyor build flakiness appears to have been resolved by Atom v0.193.0:

> Fixed issues on Windows where path too long exceptions could occur while installing/updating Atom

Consequently, going forward you should pay attention to build failures related to the AppVeyor build.

**Comment by joefitzgerald** [comment]
https://ci.appveyor.com/project/joefitzgerald/autocomplete-plus/build/508 shows two specs failing, both related to suggestion list sizing.

**Comment by joefitzgerald** [comment]
For the last failed test: https://ci.appveyor.com/project/joefitzgerald/autocomplete-plus/build/524

https://github.com/atom-community/autocomplete-plus/blob/2d48e015d86d04cb3eb525ec3d3ba7e2b4c7a1aa/spec/autocomplete-manager-integration-spec.coffee#L570-L573 will result in the suggestion list being hidden, won't it - now that the default for `backspaceTriggersAutocomplete` is `false`?

**Comment by joefitzgerald** [comment]
Same thoughts about https://github.com/atom-community/autocomplete-plus/blob/2d48e015d86d04cb3eb525ec3d3ba7e2b4c7a1aa/spec/autocomplete-manager-integration-spec.coffee#L504-L547. `backspace()` is used liberally.

**Comment by benogle** [comment]
This is pretty weird. Looks like the `::before` element on selected elements is sometimes getting interpreted by the browser as a table cell. This only happens in the specs. I cant repro in general usage:

![screen shot 2015-04-29 at 2 08 05 pm](https://cloud.githubusercontent.com/assets/69169/7401588/3e612e24-ee7a-11e4-876a-93d424579b6d.png)

![screen shot 2015-04-29 at 2 14 56 pm](https://cloud.githubusercontent.com/assets/69169/7401591/425ddfc2-ee7a-11e4-8d25-0b57b2aee97d.png)

All the other spans in the item are `display: table-cell`, and the `li` is `display: table-row`. I suppose it is maybe abuse of table rows.
