### ISSUE TITLE
Suggestion List Styling Issues

### ISSUE THREAD

**Issue by Qusic** [atom-community/autocomplete-plus#405]
### Themes Known To Have Issues

* Unity

### Scenarios Leading To Suggestion List Styling Issues

* Suggestion `text` or `snippet` or `displayText` overflow (see #351)

### Related Issues

* #399
* #410 

--

### Original Issue Report Below

I'm working on the you-complete-me provider with autocomplete-plus 2.11.0
selected row gets right aligned.
does anyone know to fix it?

![image](https://cloud.githubusercontent.com/assets/2141853/7222701/25a4c1ec-e746-11e4-8e53-6a631e16490f.png)

**Comment by benogle** [comment]
What theme are you using?

**Comment by Qusic** [comment]
I tried One Dark, One Light, Atom Dark, Atom Light.

**Comment by Qusic** [comment]
Sorry. I don't realize the UI Theme option and just changed the Syntax Theme.
The problem is gone with another UI Theme. The culprit theme is Unity.

**Comment by ctolkien** [comment]
Typescript and C# packages also impacted:

![](http://i.imgur.com/lZk6N6w.png)

![](http://i.imgur.com/dZpliwM.png)

Issue is when we have max-width and an element overflows.

Here's a codepen demonstrating the issue:

http://codepen.io/anon/pen/BNaGwN

**Comment by simurai** [comment]
Tried to look into this and it's pretty tricky.

### Fixed width
Branch: https://github.com/simurai/autocomplete-plus/tree/sm-overflow-flexbox
Changed from `float` to `flexbox` and `table-layout: fixed`. Works with truncating, but it always stays at the max-width:

![flexbox](https://cloud.githubusercontent.com/assets/378023/7541133/ce2f5100-f5ed-11e4-87cf-26d5b0e40041.gif)

### Overflow scroll
Branch: https://github.com/simurai/autocomplete-plus/tree/sm-overflow-scrolling
Another option would be to not use `table-layout: fixed` so it takes up the width of the content, just prevent wrapping. When it overflows you have to scroll to see the right labels:

![scroll](https://cloud.githubusercontent.com/assets/378023/7541163/0bb7efdc-f5ee-11e4-8d9b-78f3803b957f.gif)

### Colums
What might work better is have columns before the rows. Then they can be easier collapsed/resized with flexbox.

```html
<!-- 4 vertical columns that contain rows with items -->
<span class="icon-container"><!-- item1, item2, item3 --></span>
<span class="left-label"><!-- item1, item2, item3 --></span>
<span class="word"><!-- item1, item2, item3 --></span>
<span class="right-label"><!-- item1, item2, item3 --></span>
``` 

### Programmatic truncation
If there is a long word, it might could get truncated programmatically. And not at the end, but in the middle. That would have the benefit that you could see the end of long words that start the same.

```
// instead of
veryVeryVeryVeryVeryVeryVeryVery...
veryVeryVeryVeryVeryVeryVeryVery...

// truncate in the middle
veryVeryVeryVe...eryVeryLongWord1
veryVeryVeryVe...eryVeryLongWord2
```

**Comment by benogle** [comment]
Now it truncates let label, word, and right label based on a max width for each:

![screen shot 2015-05-08 at 1 17 12 pm](https://cloud.githubusercontent.com/assets/69169/7544732/a5a659a4-f584-11e4-9d1a-53b81859c1be.png)
![screen shot 2015-05-08 at 1 17 43 pm](https://cloud.githubusercontent.com/assets/69169/7544731/a5a2f354-f584-11e4-8838-32cad9d7ebad.png)

**Comment by benogle** [comment]
> Programmatic truncation

This would be cool. Though, I like the simplicity of the CSS approach.

**Comment by mnquintana** [comment]
@benogle With this change, is there any way to see the untruncated strings? (ie. by hovering with the mouse, selecting with the keyboard, and showing a tooltip or something)

**Comment by benogle** [comment]
Not at this time, but definitely willing to do that

**Comment by simurai** [comment]
> Now it truncates let label, word, and right label based on a max width for each:

:+1: 

I tried out the flexbox __Colums__ in this [CodePen](http://codepen.io/simurai/pen/e4800f355033e71712c41bf7b193be92/?editors=110)

![screen shot 2015-05-09 at 11 47 14 am](https://cloud.githubusercontent.com/assets/378023/7548381/34f2f27c-f641-11e4-8aa8-4872ed0933c7.png)

The nice thing would be that if everything is too long, it favors the "word" column and gives it more space (1 + 3). But if the words are all short and the labels long (2 + 4), then it doesn't truncate the labels and shows them in full.

But it requires a lot of changes, so maybe for now we can keep as is and look into it at a later point again.

**Comment by joefitzgerald** [comment]
> But it requires a lot of changes, so maybe for now we can keep as is and look into it at a later point again.

Can you rough out a list of the changes required? I'm not averse to tackling this, but need someone like you who actually knows their way around the DOM and CSS to make it happen.

**Comment by benogle** [comment]
Nice @simurai Looks like a better, more elegant solution than mine.

**Comment by simurai** [comment]
Well, it's just an "out of context" demo.. there might still be issues once it would be in Atom.

The main difference is that instead of vertical rows with items,

```html
<ol class="list-group">
  <li>
    <span class="icon-container">f</span>
    <span class="left-label">left label</span>
    <span class="word-container">
      <span class="word">word</span>
      <span class="right-label">right label</span>
    </span>
  </li>
  <li>
    <span class="icon-container">f</span>
    <span class="left-label">left label</span>
    <span class="word-container">
      <span class="word">word</span>
      <span class="right-label">right label</span>
    </span>
  </li>
</ol>
```

there would be horizontal columns with items:

```html
<ol class="list-group">
  <li class="icon-container">
    <span class="item">f</span>
    <span class="item">f</span>
  </li>
  <li class="left-label">
    <span class="item">left label</span>
    <span class="item">left label</span>
  </li>
  <li class="word">
    <span class="item">word</span>
    <span class="item">word</span>
  </li>
  <li class="right-label">
    <span class="item">right label</span>
    <span class="item">right label</span>
  </li>
</ol>
```

So a "line" would be split up and put into the 4 horizontal containers. I guess the whole template, JS and specs would need to change.. so not sure. Maybe it's better to not hold up the integration into core with this, and we can look at it again later.
