### ISSUE TITLE
Weird behaviour with snippet containing ":"

### ISSUE THREAD

**Issue by hedefalk** [atom-community/autocomplete-plus#409]
The title is a guess, but I'm trying to use a snippet for code completion on Scala code. When I do something like:

    snippet: function(${0:x: Int}, ${1:y: Int})

it correctly inserts the snippet

    foo(x: Int, y: Int)

but marks the second argument. My wild guess is that the extra ":" that I need to show the types messes it up. I do not think that displayText is a workaround since I want the types in the buffer.

Maybe this should be reported on the snippets package? Please tell me if so!

**Comment by joefitzgerald** [comment]
> but marks the second argument

I'm not sure I understand. Can you post a screenshot showing the undesired behavior?

I suspect you're right though - we do have logic that pertains to `:` in our snippet parser.

**Comment by hedefalk** [comment]
![skarmavbild 2015-04-21 kl 14 40 43](https://cloud.githubusercontent.com/assets/116520/7252347/75127afa-e834-11e4-89e8-9c88567a02e4.png)

**Comment by hedefalk** [comment]
Oh, maybe this is related. Going from using just text to snippet it also turned terrible slow. From near instant to many second (maybe 5) for just a few entries. Maybe the extra : messes something up?

**Comment by joefitzgerald** [comment]
What is the grammar in use in that screenshot? And what packages do you have installed (`apm list`)?

**Comment by benogle** [comment]
What if you start from `1` rather than `0`? 

```
{snippet: 'function(${1:x: Int}, ${2:y: Int})'}
```

**Comment by joefitzgerald** [comment]
Yes, that is the issue. You must start snippet groups from 1 not 0.

**Comment by hedefalk** [comment]
Doh! Thanks guys. I actually saw that it was 1-based but this was my code:

```coffeescript
formatParam = (param) ->
 "${#{i}:#{param[0]}: #{param[1]}}"
p = (formatParam(param, i+1) for param, i in paramList)
```
God knows which "i" I used?
