### ISSUE TITLE
Autocomplete list doesn't fit to the block anymore

### ISSUE THREAD

**Issue by itadakimas** [atom-community/autocomplete-plus#410]
Hi !

I recently came across this bug.

![screencapture](https://cloud.githubusercontent.com/assets/688408/7274682/2a91d4fa-e8ff-11e4-86cd-2c22f82f2382.png)

**Comment by joefitzgerald** [comment]
@itadakimas: what ui and syntax themes are you using? Also, what packages do you have installed (hint, run `apm list`)?

**Comment by joefitzgerald** [comment]
See also #405.

**Comment by joefitzgerald** [comment]
Finally, please make sure you are running the latest version of atom and autocomplete-plus.

**Comment by itadakimas** [comment]
I restarted Atom, and now the problem is fixed (I did nothing else).

Thanks for the help ! This package is very useful.
