### ISSUE TITLE
Autocompletion of variables in LESS not working properly

### ISSUE THREAD

**Issue by mmcbride1007** [atom-community/autocomplete-plus#411]
When I am writing in a LESS file I am unable to autocomplete on variable names. For example, if my variable name is `@primaryColor`, if I type `@prima` then press `tab`, I get `@prima:` instead of it completing `@primaryColor`.

**Comment by joefitzgerald** [comment]
@mmcbride1007 have you tried setting `Default Provider` to symbol?

**Comment by mmcbride1007** [comment]
I had not, but I just tried (changed preference and reloaded Atom) and got the same result.

**Comment by joefitzgerald** [comment]
Pictures tell a thousand words. Got any screenshots? What version of autocomplete-plus and atom are you using?

**Comment by joefitzgerald** [comment]
The ultimate solution here is for someone (hello @kevinsawicki?) to write a LESS provider for autocomplete-plus, similar to the CSS provider: https://github.com/atom/autocomplete-css. Alternatively, autocomplete-css seems to cater (at least partially) to scss, so perhaps it would be helpful to extend autocomplete-css to work on .less files also.

**Comment by joefitzgerald** [comment]
I think the reason you're having an issue with @prima with SymbolProvider and FuzzyProvider is related to #333 and #395.

**Comment by mmcbride1007** [comment]
Sure, here's a gif. I'm running Atom 0.193.0 and Autocomplete-plus 2.12.0

![autocomplete-less](https://cloud.githubusercontent.com/assets/6248612/7284021/383e724c-e900-11e4-823b-a63a1667413c.gif)

**Comment by joefitzgerald** [comment]
Could you also please post the output of `apm list`?

**Comment by joefitzgerald** [comment]
... And how much of a burden would it be to post a gist with the contents of that file? Not essential, but certainly helpful.

**Comment by mmcbride1007** [comment]
That particular one is a work file but I can put something together and show the contents of that where I'm getting the error too. `apm list` gives me:

Built-in Atom packages (85)
├── archive-view@0.55.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.24.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.73.0
├── command-palette@0.35.0
├── deprecation-cop@0.40.0
├── dev-live-reload@0.45.0
├── encoding-selector@0.19.0
├── exception-reporting@0.24.0
├── feedback@0.38.0
├── find-and-replace@0.160.0
├── fuzzy-finder@0.81.0
├── git-diff@0.54.0
├── go-to-line@0.30.0
├── grammar-selector@0.46.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.31.0
├── language-c@0.44.0
├── language-clojure@0.14.0
├── language-coffee-script@0.39.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.69.0
├── language-git@0.10.0
├── language-go@0.25.0
├── language-html@0.32.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.73.0
├── language-json@0.14.0
├── language-less@0.26.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.22.0
├── language-php@0.22.0
├── language-property-list@0.8.0
├── language-python@0.34.0
├── language-ruby@0.52.0
├── language-ruby-on-rails@0.21.0
├── language-sass@0.36.0
├── language-shellscript@0.13.0
├── language-source@0.9.0
├── language-sql@0.15.0
├── language-text@0.6.0
├── language-todo@0.18.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.148.0
├── metrics@0.45.0
├── notifications@0.40.0
├── one-dark-syntax@0.3.0
├── one-dark-ui@0.6.3
├── one-light-syntax@0.4.0
├── one-light-ui@0.5.3
├── open-on-github@0.36.0
├── package-generator@0.38.0
├── release-notes@0.52.0
├── settings-view@0.195.0
├── snippets@0.88.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.55.0
├── status-bar@0.69.0
├── styleguide@0.44.0
├── symbols-view@0.94.0
├── tabs@0.67.0
├── timecop@0.31.0
├── tree-view@0.170.0
├── update-package-dependencies@0.9.0
├── welcome@0.26.0
├── whitespace@0.29.0
└── wrap-guide@0.32.0

/Users/mcbridem/.atom/packages (8)
├── angularjs@0.2.0
├── autocomplete-plus@2.12.0
├── electron-light-syntax@1.0.0
├── electron-syntax@1.0.0
├── emmet@2.3.8
├── file-icons@1.5.4
├── less-autocompile@1.0.0
└── vim-mode@0.44.0

**Comment by joefitzgerald** [comment]
What happens if you disable:

* angularjs
* emmet
* less-autocompile
* vim-mode

Do things start working as expected then? If so, try enabling them one-by-one (disabling the others) until you can identify the conflicting package. I'm particularly interested in emmet and vim-mode.

**Comment by mmcbride1007** [comment]
Cool, I'll check that. I disabled vim-mode thinking that might do it a while ago but no luck. Emmet very well might be the culprit... stay tuned

**Comment by mmcbride1007** [comment]
Yep, the emmet package seems to be causing it. Good to know. Is this something we try to fix? Should I open an issue on that repo instead?

**Comment by joefitzgerald** [comment]
I suspect this has something to do with a conflict on the keybinding. I assume you're using `tab` for both emmet and autocomplete-plus. You have a few options. You can switch the keybinding of either emmet or autocomplete-plus away from tab. Or you can use the rather interesting solution in #86 to use both together.

**Comment by mmcbride1007** [comment]
Thanks a ton! Yeah I am using `tab` on both. I'll check that out :smile:
