### ISSUE TITLE
Feature request: don't autocomplete the same thing twice in a row.

### ISSUE THREAD

**Issue by calebmeyer** [atom-community/autocomplete-plus#419]
### To be clear: 
- I like enter as an autocomplete button. I don't want to give it up.
- I don't want this to be an enforced default, just an option

### What happens today:
- I type "test"
- "testing" shows up in the autocompletions, since it's defined earlier in this file
- I hit enter, and testing is autocompleted
- I wanted only test, so I backspace 3 times and hit enter again (attempting to go to the next line)
- testing is autocompleted again
- I backspace three times, then hit `<esc> o` (vim mode for enter normal mode > open a new line below this one)

### What I would like to happen:
- I type "test"
- "testing" shows up in the autocompletions, since it's defined earlier
- I hit enter, and testing is autocompleted
- I wanted only test, so I backspace 3 times and hit enter again.
- No autocompletions are triggered when I'm backspacing, and enter takes me to the next line.

### How to do it:
(I would PR this myself if I was fluent enough in .coffee)

The naive way to implement this fix is to disable autocompletions while backspacing. That covers my 90% case.

A better way is to remember the substring that was used for the last autocompletion (test in this case) and not autocomplete for it or any substring of it until a cursor motion (other than backspace) has happened (left, right, up, down, forward word, back word, etc). This still means I could type testi and complete testing, but that t, te, tes, and test won't trigger autocompletions.

**Comment by benogle** [comment]
> The naive way to implement this fix is to disable autocompletions while backspacing

This can be disabled in the settings. It's a bad default, and I'd like to have it disabled by default.

**Comment by joefitzgerald** [comment]
> It's a bad default

I'm just going to change the default and we can tally the bug reports. #137 and #145 were put in place to allow backspace to trigger autocomplete. But perhaps my perception of the issues associated with changing the default for `backspaceTriggersAutocomplete` from `true` to `false` don't match reality.
