### ISSUE TITLE
Incompatible with vim-mode

### ISSUE THREAD

**Issue by jasper-fu** [atom-community/autocomplete-plus#74]
When I install both 'vim-mode' and 'autocomplete-plus', it will cause lots of issues, say, when I use 'f' command in command mode, the debug console will show up like this:
![screen shot 2014-05-23 at 11 51 27](https://cloud.githubusercontent.com/assets/233379/3062922/8a75bea6-e22d-11e3-9007-4ce6e8a25d26.png)

If I uninstall either one of the package, the issue will gone.

**Comment by dcalhoun** [comment]
Yes, I am still experiencing issues with these two packages.

**Comment by joefitzgerald** [comment]
This is likely caused by a conflict in the focused element. `Object #<Input>` is the hidden input element that `autocomplete-plus` uses to allow our keybindings to work. This is probably conflicting with the element that vim-mode focuses to capture chords.

**Comment by damianesteban** [comment]
Anyone figure this out?  I really want to use Atom but lack of autocomplete with vim-mode is a problem.
